from __future__ import annotations

"""Emit people_v2 mapping YAML from the GATE 1 field spec. Run from this directory."""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent

CANONICAL = {
    "people_xw_identity": [
        "person_id",
        "worker_id",
        "source_system",
        "source_object",
        "source_id",
        "valid_from",
        "valid_to",
        "match_method",
    ],
    "people_xw_org": ["org_id", "frappe_department", "gh_department_id", "valid_from", "valid_to"],
    "people_xw_location": [
        "location_id",
        "frappe_branch",
        "gh_office_id",
        "city",
        "country",
        "region",
    ],
    "people_xw_job": ["job_id", "frappe_designation", "onet_soc_code", "job_family"],
    "people_xw_skill": ["skill_id", "frappe_skill", "onet_element_id"],
    "people_dim_org": [
        "org_id",
        "org_name",
        "parent_org_id",
        "company",
        "is_group",
        "org_path",
        "depth",
        "bg",
        "valid_from",
        "valid_to",
        "is_current",
    ],
    "people_dim_job": [
        "job_id",
        "job_name",
        "onet_soc_code",
        "job_family",
        "valid_from",
        "valid_to",
        "is_current",
    ],
    "people_dim_grade": [
        "grade_id",
        "grade_name",
        "level_rank",
        "default_salary_structure",
        "valid_from",
        "valid_to",
        "is_current",
    ],
    "people_dim_location": [
        "location_id",
        "branch_name",
        "city",
        "country",
        "region",
        "valid_from",
        "valid_to",
        "is_current",
    ],
    "people_dim_date": ["date", "month_end", "is_month_end"],
    "people_dim_appraisal_cycle": ["cycle_id", "cycle_name", "start_date", "end_date", "status"],
    "people_dim_stage": ["stage_id", "gh_job_id", "stage_name", "priority", "canonical_stage"],
    "people_dim_source": ["id", "name", "type"],
    "people_dim_rejection_reason": ["id", "name", "type"],
    "people_dim_skill": ["skill_id", "skill_name", "onet_element_id", "element_type"],
    "people_dim_learning_resource": [
        "resource_id",
        "source",
        "title",
        "url",
        "level",
        "duration_minutes",
        "roles",
        "products",
    ],
    "people_dim_survey_wave": [
        "wave_id",
        "instrument_version",
        "start_date",
        "end_date",
        "target_population",
        "response_rate",
    ],
    "people_dim_survey_item": ["item_id", "dimension", "reverse", "prompt", "instrument_version"],
    "people_dim_person": ["person_id", "first_seen_at", "first_seen_source"],
    "people_dim_person_restricted": ["person_id", "full_name", "gender", "date_of_birth"],
    "people_dim_worker": [
        "worker_id",
        "person_id",
        "frappe_employee",
        "hire_date",
        "termination_date",
        "termination_reason_raw",
        "termination_category",
        "employment_type",
        "is_rehire",
        "hired_via_application_id",
    ],
    "people_evt_worker": [
        "event_id",
        "worker_id",
        "person_id",
        "event_type",
        "event_date",
        "recorded_at",
        "source_system",
        "source_object",
        "source_id",
        "extract_id",
    ],
    "people_evt_worker_change": [
        "event_id",
        "property",
        "old_value",
        "new_value",
        "old_canonical_id",
        "new_canonical_id",
    ],
    "people_hist_worker_attr": [
        "worker_id",
        "valid_from",
        "valid_to",
        "org_id",
        "job_id",
        "grade_id",
        "location_id",
        "manager_worker_id",
        "employment_type",
        "status",
        "source_event_id",
    ],
    "people_fact_comp_assignment_restricted": [
        "comp_assignment_id",
        "worker_id",
        "from_date",
        "to_date",
        "salary_structure",
        "base",
        "variable",
        "currency",
        "source_ssa",
    ],
    "people_ref_comp_band": [
        "grade_id",
        "country",
        "currency",
        "band_min",
        "band_mid",
        "band_max",
        "valid_from",
        "valid_to",
    ],
    "people_fact_appraisal": [
        "appraisal_id",
        "worker_id",
        "cycle_id",
        "final_score",
        "total_score",
        "self_score",
        "status",
        "submitted_at",
    ],
    "people_fact_training_participation": [
        "worker_id",
        "training_event_id",
        "resource_id",
        "attendance",
        "status",
        "hours",
        "grade",
        "event_start",
    ],
    "people_fact_worker_skill": [
        "worker_id",
        "skill_id",
        "proficiency",
        "evaluation_date",
        "source_skill_map",
    ],
    "people_ref_job_skill_target": ["job_id", "skill_id", "target_proficiency", "onet_importance"],
    "people_dim_requisition": [
        "requisition_id",
        "gh_job_id",
        "gh_opening_id",
        "job_id",
        "org_id",
        "location_id",
        "hiring_manager_person_id",
        "recruiter_person_id",
        "opened_at",
        "closed_at",
        "status",
        "close_reason",
        "hired_application_id",
    ],
    "people_dim_candidate": [
        "candidate_id",
        "gh_candidate_id",
        "person_id",
        "created_at",
        "first_source_id",
    ],
    "people_fact_application": [
        "application_id",
        "candidate_id",
        "requisition_id",
        "applied_at",
        "status",
        "rejected_at",
        "hired_at",
        "source_id",
        "referrer_person_id",
        "rejection_reason_id",
        "rejection_type",
        "current_stage_id",
    ],
    "people_evt_application_stage": [
        "application_id",
        "stage_id",
        "entered_at",
        "exited_at",
        "is_current",
    ],
    "people_fact_interview": [
        "interview_id",
        "application_id",
        "stage_id",
        "start_at",
        "end_at",
        "status",
        "interviewer_person_ids",
    ],
    "people_fact_scorecard": [
        "scorecard_id",
        "application_id",
        "interview_id",
        "submitted_by_person_id",
        "submitted_at",
        "overall_recommendation",
    ],
    "people_fact_offer": [
        "offer_id",
        "version",
        "application_id",
        "requisition_id",
        "created_at",
        "sent_at",
        "resolved_at",
        "starts_at",
        "status",
    ],
    "people_dim_recruiter": [
        "person_id",
        "specialization",
        "supported_region",
        "supported_job_family",
        "valid_from",
        "valid_to",
    ],
    "people_fact_survey_score_restricted": [
        "worker_id",
        "wave_id",
        "dimension",
        "score_mean",
        "items_answered",
    ],
    "people_fact_candidate_demographic_restricted": [
        "application_id",
        "question_id",
        "answer_option_id",
        "free_form_text",
        "submitted_at",
    ],
    "people_fact_candidate_eeoc_restricted": [
        "application_id",
        "race",
        "gender",
        "veteran_status",
        "disability_status",
        "submitted_at",
    ],
    "people_ref_city": ["city", "country", "region"],
    "people_ref_separation_reason_map": ["raw_reason", "termination_category"],
}


def _entity(master_source: str, key: str, id_kind: str = "master_immutable", natural_key: str | None = None, notes: str | None = None) -> dict:
    row = {"master_source": master_source, "key": key, "id_kind": id_kind}
    if natural_key:
        row["natural_key"] = natural_key
    if notes:
        row["notes"] = notes
    return row


# GATE 2 §2.2: canonical id = master immutable id + source_system (meta). person_id is the surrogate exception.
ENTITY_META = {
    "people_xw_identity": _entity("canonical", "person_id", "surrogate", notes="person_id surrogate; worker_id = Employee.name"),
    "people_xw_org": _entity("frappe_hr", "org_id", natural_key="Department.name"),
    "people_xw_location": _entity("frappe_hr", "location_id", natural_key="Branch.name"),
    "people_xw_job": _entity("frappe_hr", "job_id", natural_key="Designation.name"),
    "people_xw_skill": _entity("frappe_hr", "skill_id", natural_key="Skill.name"),
    "people_dim_org": _entity("frappe_hr", "org_id", natural_key="Department.name"),
    "people_dim_job": _entity("frappe_hr", "job_id", natural_key="Designation.name"),
    "people_dim_grade": _entity("frappe_hr", "grade_id", natural_key="Employee Grade.name"),
    "people_dim_location": _entity("frappe_hr", "location_id", natural_key="Branch.name"),
    "people_dim_date": _entity("canonical", "date", "generated"),
    "people_dim_appraisal_cycle": _entity("frappe_hr", "cycle_id", natural_key="Appraisal Cycle.name"),
    "people_dim_stage": _entity("greenhouse_v3", "stage_id", natural_key="job_interview_stage.id"),
    "people_dim_source": _entity("greenhouse_v3", "id", natural_key="source.id"),
    "people_dim_rejection_reason": _entity("greenhouse_v3", "id", natural_key="rejection_reason.id"),
    "people_dim_skill": _entity("frappe_hr", "skill_id", natural_key="Skill.name"),
    "people_dim_learning_resource": _entity("mixed", "resource_id", notes="source column distinguishes internal Training Event vs microsoft_learn"),
    "people_dim_survey_wave": _entity("engagement_ext", "wave_id"),
    "people_dim_survey_item": _entity("engagement_ext", "item_id"),
    "people_dim_person": _entity("canonical", "person_id", "surrogate", notes="PER-sha1; exception to master-id rule"),
    "people_dim_person_restricted": _entity("canonical", "person_id", "surrogate"),
    "people_dim_worker": _entity("frappe_hr", "worker_id", natural_key="Employee.name"),
    "people_evt_worker": _entity("frappe_hr", "event_id", natural_key="source document name"),
    "people_evt_worker_change": _entity("frappe_hr", "event_id", natural_key="parent event_id + property"),
    "people_hist_worker_attr": _entity("canonical", "worker_id", notes="interval grain worker_id+valid_from; rebuilt BR-WF-008"),
    "people_fact_comp_assignment_restricted": _entity("frappe_hr", "comp_assignment_id", natural_key="Salary Structure Assignment.name"),
    "people_ref_comp_band": _entity("engagement_ext", "grade_id", notes="E1 composite with country/currency/valid_from"),
    "people_fact_appraisal": _entity("frappe_hr", "appraisal_id", natural_key="Appraisal.name"),
    "people_fact_training_participation": _entity("frappe_hr", "training_event_id", notes="grain worker+event"),
    "people_fact_worker_skill": _entity("frappe_hr", "skill_id", notes="grain worker+skill"),
    "people_ref_job_skill_target": _entity("onet", "skill_id", notes="grain job+skill"),
    "people_dim_requisition": _entity("greenhouse_v3", "requisition_id", natural_key="opening.id"),
    "people_dim_candidate": _entity("greenhouse_v3", "candidate_id", natural_key="candidate.id"),
    "people_fact_application": _entity("greenhouse_v3", "application_id", natural_key="application.id"),
    "people_evt_application_stage": _entity("greenhouse_v3", "application_id", notes="grain application+stage+entered_at"),
    "people_fact_interview": _entity("greenhouse_v3", "interview_id", natural_key="interview.id"),
    "people_fact_scorecard": _entity("greenhouse_v3", "scorecard_id", natural_key="scorecard.id"),
    "people_fact_offer": _entity("greenhouse_v3", "offer_id", natural_key="offer.id"),
    "people_dim_recruiter": _entity("canonical", "person_id", "surrogate", notes="E4; person via T8"),
    "people_fact_survey_score_restricted": _entity("engagement_ext", "worker_id", notes="grain worker+wave+dimension"),
    "people_fact_candidate_demographic_restricted": _entity("greenhouse_v3", "application_id", notes="application grain; no person/worker"),
    "people_fact_candidate_eeoc_restricted": _entity("greenhouse_v3", "application_id", notes="application grain; no person/worker"),
    "people_ref_city": _entity("engagement_ext", "city", notes="E3"),
    "people_ref_separation_reason_map": _entity("engagement_ext", "raw_reason", notes="E6"),
}


SUBMITTABLE_OBJECTS = {
    "Employee Transfer",
    "Employee Promotion",
    "Employee Separation",
    "Salary Structure Assignment",
    "Salary Structure",
    "Salary Slip",
    "Appraisal",
    "Training Event",
    "Training Result",
    "Training Feedback",
}
CHILD_DOCSTATUS_FILTER = {
    "Employee Property History": "parent.docstatus = 1",
    "Training Event Employee": "Training Event.docstatus = 1",
    "Training Result Employee": "Training Result.docstatus = 1",
}


def F(
    table,
    field,
    system,
    obj,
    src,
    trans,
    nullable,
    dtype,
    eff,
    prov,
    definition,
):
    row = {
        "canonical_table": table,
        "canonical_field": field,
        "source_system": system,
        "source_object": obj,
        "transformation": trans,
        "nullable": nullable,
        "data_type": dtype,
        "effective_date_logic": eff,
        "provenance": prov,
        "business_definition": definition,
    }
    if isinstance(src, list):
        row["source_fields"] = src
    else:
        row["source_field"] = src
    if obj in SUBMITTABLE_OBJECTS:
        row["source_filter"] = "docstatus = 1"
        row["reversal"] = "docstatus = 2 emits a reversal event (BR-DQ-001)"
    elif obj in CHILD_DOCSTATUS_FILTER:
        row["source_filter"] = CHILD_DOCSTATUS_FILTER[obj]
        row["reversal"] = "parent docstatus = 2 emits a reversal event (BR-DQ-001)"
    return row


def dump(path: Path, payload: dict) -> None:
    path.write_text(
        yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=120),
        encoding="utf-8",
    )
    print("wrote", path.name)


def file_doc(name, note, pin, fields):
    return {
        "canonical_version": "people_v2",
        "gate": 1,
        "note": note,
        "source_contract": pin,
        "fields": fields,
    }


def mappings() -> dict[str, dict]:
    scd = "SCD2 from extract diff; valid_to is next change or 9999-12-31 (BR-ORG-002)"
    xw_id = [
        F("people_xw_identity", "person_id", "canonical", "people_xw_identity", None, "generate uuid per distinct natural person", False, "uuid", "first match", "CANONICAL_KEY", "Stable person key. Never reused across people."),
        F("people_xw_identity", "worker_id", "frappe_hr", "Employee", "name", "lookup people_dim_worker.frappe_employee", True, "text", "hire_date", "CANONICAL_KEY", "Null for ATS-only person rows until T1 hire."),
        F("people_xw_identity", "source_system", "canonical", "people_xw_identity", None, "literal frappe_hr | greenhouse_v3 | engagement_ext | manual", False, "text", "row valid_from", "CANONICAL_KEY", "System that minted source_id."),
        F("people_xw_identity", "source_object", "canonical", "people_xw_identity", None, "literal Employee | user | candidate | application | offer", False, "text", "row valid_from", "CANONICAL_KEY", "Pinned source object name."),
        F("people_xw_identity", "source_id", "frappe_hr", "Employee", "name", "identity for HRIS; Harvest user.id / candidate.id / application.id / offer.id for ATS", False, "text", "row valid_from", "SOURCE_NATIVE", "Natural key in the source system."),
        F("people_xw_identity", "valid_from", "frappe_hr", "Employee", "date_of_joining", "coalesce(offer.starts_on, Employee.date_of_joining, candidate.created_at)", False, "date", "match start", "DERIVED", "Start of this identity link."),
        F("people_xw_identity", "valid_to", "canonical", "people_xw_identity", None, "next link or 9999-12-31", True, "date", "match end", "DERIVED", "End of this identity link."),
        F("people_xw_identity", "match_method", "canonical", "people_xw_identity", None, "transaction | employee_id | manual only; never name or email", False, "text", "row valid_from", "CANONICAL_KEY", "T1/T6 = transaction; T8 Harvest user.employee_id = Employee.name; else manual. Architecture F forbids email/name joins."),
        F("people_xw_identity", "source_id", "greenhouse_v3", "user", "id", "identity; link via user.employee_id = Employee.name (T8)", False, "text", "user.created_at", "SOURCE_NATIVE", "Harvest user row. Match method employee_id. Do not use primary_email."),
        F("people_xw_identity", "source_id", "greenhouse_v3", "candidate", "id", "identity; person_id filled after T1 (accepted offer + Employee)", True, "text", "candidate.created_at", "SOURCE_NATIVE", "Pre-hire candidate identity. worker_id stays null until T1."),
        F("people_xw_identity", "match_method", "greenhouse_v3", "offer", "id", "transaction when offer.status=Accepted and Employee.name is created from T1", False, "text", "offer.starts_on", "CANONICAL_KEY", "T1 hire transaction links candidate/application/offer to the new Employee."),
    ]
    out = {
        "canonical_model.yml": {
            "canonical_version": "people_v2",
            "architecture": "docs/PEOPLE_DATA_ARCHITECTURE.md",
            "section": "5",
            "note": "Silver column inventory for GATE 1 coverage. Gold/marts are out of scope.",
            "tables": [
                {"name": name, "columns": cols, "schema": "people_v2", **ENTITY_META.get(name, {})}
                for name, cols in CANONICAL.items()
            ],
        },
        "bronze_ingest.yml": {
            "canonical_version": "people_v2",
            "lake_path": "people_bronze/<source_system>/<object>/extract_date=YYYY-MM-DD/run_id=<id>/part-*.parquet",
            "fields": [
                F("people_bronze", "_source_system", "ingest", "manifest", "source_system", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Pinned source system id (frappe_hr, greenhouse_v3, onet, bls, microsoft_learn, engagement_ext)."),
                F("people_bronze", "_source_object", "ingest", "manifest", "source_object", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Pinned object name (Employee, application, …)."),
                F("people_bronze", "_source_version", "ingest", "manifest", "source_version", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Pin tag (hrms v16.15.0, Harvest v3, db_31_0_text)."),
                F("people_bronze", "_source_id", "ingest", "payload", "natural_key", "identity", False, "text", "extract_ts", "SOURCE_NATIVE", "Source primary key (Employee.name / Harvest id)."),
                F("people_bronze", "_extract_id", "ingest", "people_meta_extract_run", "extract_id", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Extract run that wrote this file."),
                F("people_bronze", "_extract_ts", "ingest", "manifest", "extract_ts", "identity", False, "timestamptz", "extract_ts", "CANONICAL_KEY", "UTC write time."),
                F("people_bronze", "_row_hash", "ingest", "payload", "payload", "sha256 of canonicalized JSON", False, "text", "extract_ts", "DERIVED", "Change detection for SCD2."),
                F("people_bronze", "payload", "ingest", "source", None, "JSON string of the source-shaped record", False, "text", "extract_ts", "SOURCE_NATIVE", "Immutable source document."),
                F("people_meta_extract_run", "extract_id", "ingest", "manifest", "extract_id", "identity", False, "text", "started_at", "CANONICAL_KEY", "Primary key of an extract."),
                F("people_meta_extract_run", "run_id", "ingest", "manifest", "run_id", "identity", False, "text", "started_at", "CANONICAL_KEY", "Pipeline run grouping extracts."),
                F("people_meta_extract_run", "source_system", "ingest", "manifest", "source_system", "identity", False, "text", "started_at", "CANONICAL_KEY", "Same as bronze _source_system."),
                F("people_meta_extract_run", "source_object", "ingest", "manifest", "source_object", "identity", False, "text", "started_at", "CANONICAL_KEY", "Same as bronze _source_object."),
                F("people_meta_extract_run", "extract_date", "ingest", "manifest", "extract_date", "identity", False, "date", "extract_date", "CANONICAL_KEY", "Partition date."),
                F("people_meta_extract_run", "mode", "ingest", "manifest", "mode", "full or incremental", False, "text", "started_at", "CANONICAL_KEY", "Extract mode."),
                F("people_meta_extract_run", "control_total", "ingest", "manifest", "control_total", "identity", True, "integer", "finished_at", "SOURCE_NATIVE", "Source-reported row count."),
                F("people_meta_extract_run", "rows_received", "ingest", "manifest", "rows_received", "identity", False, "integer", "finished_at", "DERIVED", "Rows written to bronze."),
                F("people_meta_extract_run", "status", "ingest", "manifest", "status", "identity", False, "text", "finished_at", "CANONICAL_KEY", "success | failed."),
                F("people_meta_extract_run", "started_at", "ingest", "manifest", "started_at", "identity", False, "timestamptz", "started_at", "CANONICAL_KEY", "Extract start."),
                F("people_meta_extract_run", "finished_at", "ingest", "manifest", "finished_at", "identity", True, "timestamptz", "finished_at", "CANONICAL_KEY", "Extract end."),
                F("people_meta_extract_run", "scenario_ids", "ingest", "manifest", "scenario_ids", "identity", True, "text[]", "started_at", "CANONICAL_KEY", "Simulator scenarios that produced this extract. Empty for live pins."),
            ],
        },
        "people_xw_identity.yml": file_doc(
            "xw_identity",
            "Identity links. Allowed match_method: transaction | employee_id | manual. Name/email joins are forbidden (architecture F / §5.1). Conflicts with SOURCE_CONTRACT_FIRST email join.",
            {"frappe_hr": "v16.15.0", "greenhouse": "Harvest v3", "docs": "docs/PEOPLE_CONTRACT_FIELD_CHECK.md"},
            xw_id,
        ),
        "people_xw_org.yml": file_doc(
            "xw_org",
            "Greenhouse department is not Frappe Department. Mapping is explicit and versioned.",
            {"frappe": "erpnext_doctypes/department.json", "greenhouse": "schemas/fields/department.fields.json"},
            [
                F("people_xw_org", "org_id", "frappe_hr", "Department", "name", "canonical org key = Frappe Department.name", False, "text", scd, "CANONICAL_KEY", "Org spine is HRIS department."),
                F("people_xw_org", "frappe_department", "frappe_hr", "Department", "name", "identity", False, "text", scd, "SOURCE_NATIVE", "Frappe Department.name."),
                F("people_xw_org", "gh_department_id", "greenhouse_v3", "department", "id", "manual or employee_id-backed map of GH department.id to Frappe Department.name; never name-match", True, "integer", scd, "CANONICAL_KEY", "Null until an explicit crosswalk row is approved."),
                F("people_xw_org", "valid_from", "frappe_hr", "Department", "modified", "SCD2 start (BR-ORG-002)", False, "date", scd, "DERIVED", "When this GH↔Frappe pair became valid."),
                F("people_xw_org", "valid_to", "frappe_hr", "Department", "modified", "SCD2 end (BR-ORG-002)", True, "date", scd, "DERIVED", "When this pair was replaced."),
            ],
        ),
        "people_xw_location.yml": file_doc(
            "xw_location",
            "Branch has only a name. City/country/region come from people_ref_city (E3).",
            {"frappe": "erpnext_doctypes/branch.json", "greenhouse": "schemas/fields/office.fields.json"},
            [
                F("people_xw_location", "location_id", "frappe_hr", "Branch", "name", "canonical location key = Branch.name", False, "text", scd, "CANONICAL_KEY", "Location spine is HRIS branch."),
                F("people_xw_location", "frappe_branch", "frappe_hr", "Branch", "name", "identity", False, "text", scd, "SOURCE_NATIVE", "Frappe Branch.name."),
                F("people_xw_location", "gh_office_id", "greenhouse_v3", "office", "id", "explicit map; office.location is free-text and is not the join key", True, "integer", scd, "CANONICAL_KEY", "Null until approved."),
                F("people_xw_location", "city", "engagement_ext", "people_ref_city", "city", "lookup E3 by branch_name", True, "text", scd, "SYNTHETIC_EXTENSION", "E3. Frappe Branch has no city field."),
                F("people_xw_location", "country", "engagement_ext", "people_ref_city", "country", "lookup E3", True, "text", scd, "SYNTHETIC_EXTENSION", "E3."),
                F("people_xw_location", "region", "engagement_ext", "people_ref_city", "region", "lookup E3", True, "text", scd, "SYNTHETIC_EXTENSION", "E3."),
            ],
        ),
        "people_xw_job.yml": file_doc(
            "xw_job",
            "Designation to O*NET-SOC is constructed 1:1 in the simulator; live orgs must supply the same table.",
            {"frappe": "erpnext_doctypes/designation.json", "onet": "db_31_0_text Occupation Data.txt"},
            [
                F("people_xw_job", "job_id", "frappe_hr", "Designation", "name", "canonical job key = Designation.name", False, "text", scd, "CANONICAL_KEY", "Job spine is HRIS designation."),
                F("people_xw_job", "frappe_designation", "frappe_hr", "Designation", "name", "identity", False, "text", scd, "SOURCE_NATIVE", "Frappe Designation.name."),
                F("people_xw_job", "onet_soc_code", "onet", "Occupation Data.txt", "O*NET-SOC Code", "1:1 constructed map from Designation to SOC", True, "text", scd, "CANONICAL_KEY", "O*NET occupation code."),
                F("people_xw_job", "job_family", "onet", "Occupation Data.txt", "O*NET-SOC Code", "SOC major group = first two digits (BR-WF-005)", True, "text", scd, "DERIVED", "Job family from SOC major group."),
            ],
        ),
        "people_xw_skill.yml": file_doc(
            "xw_skill",
            "Frappe Skill rows are constructed 1:1 with O*NET elements.",
            {"frappe": "doctypes/skill.json", "onet": "Essential Skills.txt / Knowledge.txt"},
            [
                F("people_xw_skill", "skill_id", "frappe_hr", "Skill", "name", "canonical skill key = Skill.name", False, "text", "current", "CANONICAL_KEY", "Skill spine is Frappe Skill."),
                F("people_xw_skill", "frappe_skill", "frappe_hr", "Skill", "name", "identity", False, "text", "current", "SOURCE_NATIVE", "Frappe Skill.name."),
                F("people_xw_skill", "onet_element_id", "onet", "Essential Skills.txt", "Element ID", "1:1 constructed map", True, "text", "current", "CANONICAL_KEY", "O*NET element id."),
            ],
        ),
    }
    from emit_v2_ats import ext_mappings, greenhouse_mappings

    out.update(frappe_mappings())
    out.update(greenhouse_mappings())
    out.update(ext_mappings())
    return out


SCD = "SCD2 from extract diff; valid_to is next change or 9999-12-31 (BR-ORG-002)"


def frappe_mappings() -> dict:
    return {
        "frappe_department.yml": file_doc(
            "dim_org",
            "Frappe Department is the org spine. org_path/depth/bg are derived. E7 supplies GlobalTech names in the simulator.",
            {"pin": "erpnext_doctypes/department.json"},
            [
                F("people_dim_org", "org_id", "frappe_hr", "Department", "name", "identity", False, "text", SCD, "CANONICAL_KEY", "Department.name."),
                F("people_dim_org", "org_name", "frappe_hr", "Department", "department_name", "identity; simulator overlay from E7", False, "text", SCD, "SOURCE_NATIVE", "Display name."),
                F("people_dim_org", "parent_org_id", "frappe_hr", "Department", "parent_department", "identity", True, "text", SCD, "SOURCE_NATIVE", "Parent Department.name."),
                F("people_dim_org", "company", "frappe_hr", "Department", "company", "identity", False, "text", SCD, "SOURCE_NATIVE", "Company link."),
                F("people_dim_org", "is_group", "frappe_hr", "Department", "is_group", "identity", False, "boolean", SCD, "SOURCE_NATIVE", "Group node flag."),
                F("people_dim_org", "org_path", "frappe_hr", "Department", ["name", "parent_department"], "ltree from ancestor names (BR-ORG-001)", False, "ltree", SCD, "DERIVED", "Path for @> org rollups."),
                F("people_dim_org", "depth", "frappe_hr", "Department", ["name", "parent_department"], "nlevel(org_path) (BR-ORG-001)", False, "integer", SCD, "DERIVED", "Tree depth."),
                F("people_dim_org", "bg", "frappe_hr", "Department", ["name", "parent_department"], "root ancestor org_id (BR-ORG-001); E7 names the GlobalTech BGs", False, "text", SCD, "DERIVED", "Business group."),
                F("people_dim_org", "valid_from", "frappe_hr", "Department", "modified", "SCD2 start (BR-ORG-002)", False, "date", SCD, "DERIVED", "Version start."),
                F("people_dim_org", "valid_to", "frappe_hr", "Department", "modified", "SCD2 end (BR-ORG-002)", True, "date", SCD, "DERIVED", "Version end."),
                F("people_dim_org", "is_current", "frappe_hr", "Department", "modified", "valid_to is null (BR-ORG-002)", False, "boolean", SCD, "DERIVED", "Current version flag."),
            ],
        ),
        "frappe_designation.yml": file_doc(
            "dim_job",
            "Designation is the job spine. job_family from O*NET SOC (BR-WF-005).",
            {"pin": "erpnext_doctypes/designation.json"},
            [
                F("people_dim_job", "job_id", "frappe_hr", "Designation", "name", "identity", False, "text", SCD, "CANONICAL_KEY", "Designation.name."),
                F("people_dim_job", "job_name", "frappe_hr", "Designation", "designation_name", "identity", False, "text", SCD, "SOURCE_NATIVE", "Display name."),
                F("people_dim_job", "onet_soc_code", "onet", "Occupation Data.txt", "O*NET-SOC Code", "via people_xw_job", True, "text", SCD, "CANONICAL_KEY", "SOC from crosswalk."),
                F("people_dim_job", "job_family", "onet", "Occupation Data.txt", "O*NET-SOC Code", "SOC major group (BR-WF-005)", True, "text", SCD, "DERIVED", "SOC major group."),
                F("people_dim_job", "valid_from", "frappe_hr", "Designation", "modified", "SCD2 start (BR-ORG-002)", False, "date", SCD, "DERIVED", "Version start."),
                F("people_dim_job", "valid_to", "frappe_hr", "Designation", "modified", "SCD2 end (BR-ORG-002)", True, "date", SCD, "DERIVED", "Version end."),
                F("people_dim_job", "is_current", "frappe_hr", "Designation", "modified", "valid_to is null", False, "boolean", SCD, "DERIVED", "Current version flag."),
            ],
        ),
        "frappe_grade.yml": file_doc(
            "dim_grade",
            "Employee Grade has no sort order. level_rank is E2. Current worker grade comes from Salary Structure Assignment.grade, not Employee.",
            {"pin": "doctypes/employee_grade.json"},
            [
                F("people_dim_grade", "grade_id", "frappe_hr", "Employee Grade", "name", "identity", False, "text", SCD, "CANONICAL_KEY", "Employee Grade.name."),
                F("people_dim_grade", "grade_name", "frappe_hr", "Employee Grade", "name", "identity", False, "text", SCD, "SOURCE_NATIVE", "Grade label."),
                F("people_dim_grade", "level_rank", "engagement_ext", "people_ref_grade_rank", "level_rank", "integer rank from compensation architecture (E2)", False, "integer", SCD, "SYNTHETIC_EXTENSION", "E2. Employee Grade has no rank field."),
                F("people_dim_grade", "default_salary_structure", "frappe_hr", "Employee Grade", "default_salary_structure", "identity", True, "text", SCD, "SOURCE_NATIVE", "Default Salary Structure link."),
                F("people_dim_grade", "valid_from", "frappe_hr", "Employee Grade", "modified", "SCD2 start", False, "date", SCD, "DERIVED", "Version start."),
                F("people_dim_grade", "valid_to", "frappe_hr", "Employee Grade", "modified", "SCD2 end", True, "date", SCD, "DERIVED", "Version end."),
                F("people_dim_grade", "is_current", "frappe_hr", "Employee Grade", "modified", "valid_to is null", False, "boolean", SCD, "DERIVED", "Current version flag."),
            ],
        ),
        "frappe_branch.yml": file_doc(
            "dim_location",
            "Branch has only branch name. Geography is E3.",
            {"pin": "erpnext_doctypes/branch.json"},
            [
                F("people_dim_location", "location_id", "frappe_hr", "Branch", "name", "identity", False, "text", SCD, "CANONICAL_KEY", "Branch.name."),
                F("people_dim_location", "branch_name", "frappe_hr", "Branch", "branch", "identity", False, "text", SCD, "SOURCE_NATIVE", "Branch label."),
                F("people_dim_location", "city", "engagement_ext", "people_ref_city", "city", "E3 lookup", True, "text", SCD, "SYNTHETIC_EXTENSION", "E3."),
                F("people_dim_location", "country", "engagement_ext", "people_ref_city", "country", "E3 lookup", True, "text", SCD, "SYNTHETIC_EXTENSION", "E3."),
                F("people_dim_location", "region", "engagement_ext", "people_ref_city", "region", "E3 lookup", True, "text", SCD, "SYNTHETIC_EXTENSION", "E3."),
                F("people_dim_location", "valid_from", "frappe_hr", "Branch", "modified", "SCD2 start", False, "date", SCD, "DERIVED", "Version start."),
                F("people_dim_location", "valid_to", "frappe_hr", "Branch", "modified", "SCD2 end", True, "date", SCD, "DERIVED", "Version end."),
                F("people_dim_location", "is_current", "frappe_hr", "Branch", "modified", "valid_to is null", False, "boolean", SCD, "DERIVED", "Current version flag."),
            ],
        ),
        "frappe_employee.yml": file_doc(
            "person_worker",
            "Employee effective schema = ERPNext employee.json + HRMS custom fields. employment_type and grade are SOURCE_NATIVE (hrms/setup.py). E8 withdrawn.",
            {"pin": ["erpnext_doctypes/employee.json", "custom_fields.json", "erpnext_doctypes/employee_effective.fields.json"]},
            [
                F("people_dim_person", "person_id", "frappe_hr", "Employee", "name", "uuid from xw_identity where source_object=Employee", False, "uuid", "date_of_joining", "CANONICAL_KEY", "Person key. No PII."),
                F("people_dim_person", "first_seen_at", "frappe_hr", "Employee", "creation", "min(creation, candidate.created_at) across xw rows", False, "timestamptz", "first_seen_at", "DERIVED", "Earliest sighting."),
                F("people_dim_person", "first_seen_source", "frappe_hr", "Employee", "name", "frappe_hr if Employee precedes candidate else greenhouse_v3", False, "text", "first_seen_at", "DERIVED", "System of first sighting."),
                F("people_dim_person_restricted", "person_id", "frappe_hr", "Employee", "name", "same as people_dim_person", False, "uuid", "date_of_joining", "CANONICAL_KEY", "Restricted PII key."),
                F("people_dim_person_restricted", "full_name", "frappe_hr", "Employee", "employee_name", "identity", False, "text", "current", "SOURCE_NATIVE", "Employee.employee_name."),
                F("people_dim_person_restricted", "gender", "frappe_hr", "Employee", "gender", "identity", True, "text", "current", "SOURCE_NATIVE", "HRIS gender. Never from Harvest EEOC (BR-GOV-001)."),
                F("people_dim_person_restricted", "date_of_birth", "frappe_hr", "Employee", "date_of_birth", "identity", True, "date", "current", "SOURCE_NATIVE", "HRIS DOB."),
                F("people_dim_worker", "worker_id", "frappe_hr", "Employee", "name", "identity; one spell per Employee.name unless create_new_employee_id transfer", False, "text", "date_of_joining", "CANONICAL_KEY", "Equals Employee.name."),
                F("people_dim_worker", "person_id", "frappe_hr", "Employee", "name", "xw_identity", False, "uuid", "date_of_joining", "CANONICAL_KEY", "Person of this spell."),
                F("people_dim_worker", "frappe_employee", "frappe_hr", "Employee", "name", "identity", False, "text", "date_of_joining", "SOURCE_NATIVE", "Employee.name."),
                F("people_dim_worker", "hire_date", "frappe_hr", "Employee", "date_of_joining", "identity; T1 backfill from offer.starts_on when Employee is created from accepted offer", False, "date", "date_of_joining", "SOURCE_NATIVE", "First day of this spell."),
                F("people_dim_worker", "termination_date", "frappe_hr", "Employee", "relieving_date", "identity", True, "date", "relieving_date", "SOURCE_NATIVE", "Last day. Null while employed."),
                F("people_dim_worker", "termination_reason_raw", "frappe_hr", "Employee", "reason_for_leaving", "identity", True, "text", "relieving_date", "SOURCE_NATIVE", "Free text. Mapped via E6."),
                F("people_dim_worker", "termination_category", "engagement_ext", "people_ref_separation_reason_map", "termination_category", "map reason_for_leaving through E6 (BR-RET-001)", True, "text", "relieving_date", "DERIVED", "voluntary | involuntary | other."),
                F("people_dim_worker", "employment_type", "frappe_hr", "Employee", "employment_type", "identity; HRMS custom field Link Employment Type", True, "text", SCD, "SOURCE_NATIVE", "HRMS custom field on Employee (hrms/setup.py). Not on ERPNext Employee.json. Values are Employment Type.name."),
                F("people_dim_worker", "is_rehire", "frappe_hr", "Employee", "name", "true when person_id already has an earlier worker_id (BR-WF-006)", False, "boolean", "date_of_joining", "DERIVED", "Rehire flag."),
                F("people_dim_worker", "hired_via_application_id", "greenhouse_v3", "offer", "application_id", "T1: accepted offer whose starts_on = date_of_joining; null for pre-ATS hires", True, "bigint", "date_of_joining", "CANONICAL_KEY", "Application that produced this hire."),
                F("people_evt_worker", "event_id", "frappe_hr", "Employee", "name", "hash(source_system, source_object, source_id, event_type, event_date)", False, "text", "date_of_joining", "CANONICAL_KEY", "Hire event id."),
                F("people_evt_worker", "worker_id", "frappe_hr", "Employee", "name", "identity", False, "text", "date_of_joining", "CANONICAL_KEY", "Worker of the hire event."),
                F("people_evt_worker", "person_id", "frappe_hr", "Employee", "name", "xw_identity", False, "uuid", "date_of_joining", "CANONICAL_KEY", "Person of the hire event."),
                F("people_evt_worker", "event_type", "frappe_hr", "Employee", "date_of_joining", "hire or rehire (BR-WF-006)", False, "text", "date_of_joining", "DERIVED", "hire | rehire from Employee insert."),
                F("people_evt_worker", "event_date", "frappe_hr", "Employee", "date_of_joining", "identity", False, "date", "date_of_joining", "SOURCE_NATIVE", "Business effective date of hire."),
                F("people_evt_worker", "recorded_at", "frappe_hr", "Employee", "creation", "identity", False, "timestamptz", "creation", "SOURCE_NATIVE", "DocType creation."),
                F("people_evt_worker", "source_system", "frappe_hr", "Employee", None, "literal frappe_hr", False, "text", "creation", "CANONICAL_KEY", "HRIS."),
                F("people_evt_worker", "source_object", "frappe_hr", "Employee", None, "literal Employee", False, "text", "creation", "CANONICAL_KEY", "Employee (not extract diff)."),
                F("people_evt_worker", "source_id", "frappe_hr", "Employee", "name", "identity", False, "text", "creation", "SOURCE_NATIVE", "Employee.name."),
                F("people_evt_worker", "extract_id", "ingest", "people_meta_extract_run", "extract_id", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Extract that observed the hire."),
            ],
        ),
        "frappe_employee_transfer.yml": file_doc(
            "transfer",
            "Child table is Employee Property History (property, current, new, fieldname).",
            {"pin": ["doctypes/employee_transfer.json", "doctypes/employee_property_history.json"]},
            [
                F("people_evt_worker", "event_id", "frappe_hr", "Employee Transfer", "name", "identity", False, "text", "transfer_date", "CANONICAL_KEY", "Transfer document name."),
                F("people_evt_worker", "worker_id", "frappe_hr", "Employee Transfer", "employee", "identity", False, "text", "transfer_date", "SOURCE_NATIVE", "Employee.link."),
                F("people_evt_worker", "person_id", "frappe_hr", "Employee Transfer", "employee", "xw_identity", False, "uuid", "transfer_date", "CANONICAL_KEY", "Person of the worker."),
                F("people_evt_worker", "event_type", "frappe_hr", "Employee Transfer", None, "literal transfer", False, "text", "transfer_date", "CANONICAL_KEY", "transfer."),
                F("people_evt_worker", "event_date", "frappe_hr", "Employee Transfer", "transfer_date", "identity", False, "date", "transfer_date", "SOURCE_NATIVE", "Transfer effective date."),
                F("people_evt_worker", "recorded_at", "frappe_hr", "Employee Transfer", "creation", "identity", False, "timestamptz", "creation", "SOURCE_NATIVE", "Document creation."),
                F("people_evt_worker", "source_system", "frappe_hr", "Employee Transfer", None, "literal frappe_hr", False, "text", "creation", "CANONICAL_KEY", "HRIS."),
                F("people_evt_worker", "source_object", "frappe_hr", "Employee Transfer", None, "literal Employee Transfer", False, "text", "creation", "CANONICAL_KEY", "Parent DocType."),
                F("people_evt_worker", "source_id", "frappe_hr", "Employee Transfer", "name", "identity", False, "text", "creation", "SOURCE_NATIVE", "Transfer.name."),
                F("people_evt_worker", "extract_id", "ingest", "people_meta_extract_run", "extract_id", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Extract id."),
                F("people_evt_worker_change", "event_id", "frappe_hr", "Employee Transfer", "name", "parent event_id", False, "text", "transfer_date", "CANONICAL_KEY", "Parent transfer."),
                F("people_evt_worker_change", "property", "frappe_hr", "Employee Property History", "fieldname", "coalesce(fieldname, property) mapped to department|designation|grade|branch|reports_to|employment_type|status|base|variable", False, "text", "transfer_date", "SOURCE_NESTED", "Changed attribute."),
                F("people_evt_worker_change", "old_value", "frappe_hr", "Employee Property History", "current", "identity", True, "text", "transfer_date", "SOURCE_NESTED", "Value before the transfer."),
                F("people_evt_worker_change", "new_value", "frappe_hr", "Employee Property History", "new", "identity", True, "text", "transfer_date", "SOURCE_NESTED", "Value after the transfer."),
                F("people_evt_worker_change", "old_canonical_id", "frappe_hr", "Employee Property History", "current", "resolve through xw when property is department/designation/grade/branch/reports_to", True, "text", "transfer_date", "DERIVED", "Canonical id of old_value."),
                F("people_evt_worker_change", "new_canonical_id", "frappe_hr", "Employee Property History", "new", "resolve through xw", True, "text", "transfer_date", "DERIVED", "Canonical id of new_value."),
            ],
        ),
        "frappe_employee_promotion.yml": file_doc(
            "promotion",
            "Child table is Employee Property History on promotion_details.",
            {"pin": ["doctypes/employee_promotion.json", "doctypes/employee_property_history.json"]},
            [
                F("people_evt_worker", "event_id", "frappe_hr", "Employee Promotion", "name", "identity", False, "text", "promotion_date", "CANONICAL_KEY", "Promotion document name."),
                F("people_evt_worker", "worker_id", "frappe_hr", "Employee Promotion", "employee", "identity", False, "text", "promotion_date", "SOURCE_NATIVE", "Employee.link."),
                F("people_evt_worker", "person_id", "frappe_hr", "Employee Promotion", "employee", "xw_identity", False, "uuid", "promotion_date", "CANONICAL_KEY", "Person of the worker."),
                F("people_evt_worker", "event_type", "frappe_hr", "Employee Promotion", None, "literal promotion", False, "text", "promotion_date", "CANONICAL_KEY", "promotion."),
                F("people_evt_worker", "event_date", "frappe_hr", "Employee Promotion", "promotion_date", "identity", False, "date", "promotion_date", "SOURCE_NATIVE", "Promotion effective date."),
                F("people_evt_worker", "recorded_at", "frappe_hr", "Employee Promotion", "creation", "identity", False, "timestamptz", "creation", "SOURCE_NATIVE", "Document creation."),
                F("people_evt_worker", "source_system", "frappe_hr", "Employee Promotion", None, "literal frappe_hr", False, "text", "creation", "CANONICAL_KEY", "HRIS."),
                F("people_evt_worker", "source_object", "frappe_hr", "Employee Promotion", None, "literal Employee Promotion", False, "text", "creation", "CANONICAL_KEY", "Parent DocType."),
                F("people_evt_worker", "source_id", "frappe_hr", "Employee Promotion", "name", "identity", False, "text", "creation", "SOURCE_NATIVE", "Promotion.name."),
                F("people_evt_worker", "extract_id", "ingest", "people_meta_extract_run", "extract_id", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Extract id."),
                F("people_evt_worker_change", "event_id", "frappe_hr", "Employee Promotion", "name", "parent event_id", False, "text", "promotion_date", "CANONICAL_KEY", "Parent promotion."),
                F("people_evt_worker_change", "property", "frappe_hr", "Employee Property History", "fieldname", "same mapping as transfer", False, "text", "promotion_date", "SOURCE_NESTED", "Changed attribute."),
                F("people_evt_worker_change", "old_value", "frappe_hr", "Employee Property History", "current", "identity", True, "text", "promotion_date", "SOURCE_NESTED", "Value before."),
                F("people_evt_worker_change", "new_value", "frappe_hr", "Employee Property History", "new", "identity", True, "text", "promotion_date", "SOURCE_NESTED", "Value after."),
                F("people_evt_worker_change", "old_canonical_id", "frappe_hr", "Employee Property History", "current", "xw resolve", True, "text", "promotion_date", "DERIVED", "Canonical old id."),
                F("people_evt_worker_change", "new_canonical_id", "frappe_hr", "Employee Property History", "new", "xw resolve", True, "text", "promotion_date", "DERIVED", "Canonical new id."),
            ],
        ),
        "frappe_employee_separation.yml": file_doc(
            "separation",
            "Employee Separation is process evidence. Termination date and reason remain on Employee.",
            {"pin": "doctypes/employee_separation.json"},
            [
                F("people_evt_worker", "event_id", "frappe_hr", "Employee Separation", "name", "identity", False, "text", "boarding_begins_on", "CANONICAL_KEY", "Separation document name."),
                F("people_evt_worker", "worker_id", "frappe_hr", "Employee Separation", "employee", "identity", False, "text", "boarding_begins_on", "SOURCE_NATIVE", "Employee.link."),
                F("people_evt_worker", "person_id", "frappe_hr", "Employee Separation", "employee", "xw_identity", False, "uuid", "boarding_begins_on", "CANONICAL_KEY", "Person of the worker."),
                F("people_evt_worker", "event_type", "frappe_hr", "Employee Separation", None, "literal separation", False, "text", "boarding_begins_on", "CANONICAL_KEY", "separation."),
                F("people_evt_worker", "event_date", "frappe_hr", "Employee", "relieving_date", "prefer Employee.relieving_date; fallback boarding_begins_on", False, "date", "relieving_date", "SOURCE_NATIVE", "Last day of employment."),
                F("people_evt_worker", "recorded_at", "frappe_hr", "Employee Separation", "creation", "identity", False, "timestamptz", "creation", "SOURCE_NATIVE", "Document creation."),
                F("people_evt_worker", "source_system", "frappe_hr", "Employee Separation", None, "literal frappe_hr", False, "text", "creation", "CANONICAL_KEY", "HRIS."),
                F("people_evt_worker", "source_object", "frappe_hr", "Employee Separation", None, "literal Employee Separation", False, "text", "creation", "CANONICAL_KEY", "Process evidence."),
                F("people_evt_worker", "source_id", "frappe_hr", "Employee Separation", "name", "identity", False, "text", "creation", "SOURCE_NATIVE", "Separation.name."),
                F("people_evt_worker", "extract_id", "ingest", "people_meta_extract_run", "extract_id", "identity", False, "text", "extract_ts", "CANONICAL_KEY", "Extract id."),
                F("people_evt_worker_change", "event_id", "frappe_hr", "Employee Separation", "name", "parent event_id", False, "text", "relieving_date", "CANONICAL_KEY", "Separation event."),
                F("people_evt_worker_change", "property", "frappe_hr", "Employee", "status", "literal status", False, "text", "relieving_date", "DERIVED", "Status change to Left (BR-WF-007)."),
                F("people_evt_worker_change", "old_value", "frappe_hr", "Employee", "status", "prior status", True, "text", "relieving_date", "DERIVED", "Status before Left."),
                F("people_evt_worker_change", "new_value", "frappe_hr", "Employee", "status", "literal Left", True, "text", "relieving_date", "SOURCE_NATIVE", "Terminal status."),
                F("people_evt_worker_change", "old_canonical_id", "frappe_hr", "Employee", "status", "identity", True, "text", "relieving_date", "DERIVED", "Old status token."),
                F("people_evt_worker_change", "new_canonical_id", "frappe_hr", "Employee", "status", "literal Left", True, "text", "relieving_date", "DERIVED", "New status token."),
            ],
        ),
        "frappe_salary_assignment.yml": file_doc(
            "comp",
            "Restricted. Grade for the worker as-of a date comes from SSA.grade, not Employee.",
            {"pin": "doctypes/salary_structure_assignment.json"},
            [
                F("people_fact_comp_assignment_restricted", "comp_assignment_id", "frappe_hr", "Salary Structure Assignment", "name", "identity", False, "text", "from_date", "CANONICAL_KEY", "SSA.name."),
                F("people_fact_comp_assignment_restricted", "worker_id", "frappe_hr", "Salary Structure Assignment", "employee", "identity", False, "text", "from_date", "SOURCE_NATIVE", "Employee.link."),
                F("people_fact_comp_assignment_restricted", "from_date", "frappe_hr", "Salary Structure Assignment", "from_date", "identity", False, "date", "from_date", "SOURCE_NATIVE", "Assignment start."),
                F("people_fact_comp_assignment_restricted", "to_date", "frappe_hr", "Salary Structure Assignment", "from_date", "lead(from_date) over worker - 1 day, then least(that, Employee.relieving_date) so to_date ≤ termination_date (BR-COMP-002)", True, "date", "from_date", "DERIVED", "Day before the next SSA, capped by termination_date."),
                F("people_fact_comp_assignment_restricted", "salary_structure", "frappe_hr", "Salary Structure Assignment", "salary_structure", "identity", False, "text", "from_date", "SOURCE_NATIVE", "Salary Structure link."),
                F("people_fact_comp_assignment_restricted", "base", "frappe_hr", "Salary Structure Assignment", "base", "identity", True, "numeric", "from_date", "SOURCE_NATIVE", "Base pay."),
                F("people_fact_comp_assignment_restricted", "variable", "frappe_hr", "Salary Structure Assignment", "variable", "identity", True, "numeric", "from_date", "SOURCE_NATIVE", "Variable pay."),
                F("people_fact_comp_assignment_restricted", "currency", "frappe_hr", "Salary Structure Assignment", "currency", "identity", False, "text", "from_date", "SOURCE_NATIVE", "Currency."),
                F("people_fact_comp_assignment_restricted", "source_ssa", "frappe_hr", "Salary Structure Assignment", "name", "identity", False, "text", "from_date", "SOURCE_NATIVE", "Provenance SSA.name."),
                F("people_hist_worker_attr", "grade_id", "frappe_hr", "Employee", "grade", "as-of from Employee.grade (HRMS custom field). SSA.grade remains the payroll assignment grade.", True, "text", "from_date", "SOURCE_NATIVE", "Current worker grade from HRMS custom field Employee.grade."),
                F("people_evt_worker", "event_type", "frappe_hr", "Salary Structure Assignment", "from_date", "literal comp_change when base/variable/grade changes", False, "text", "from_date", "DERIVED", "Compensation change event."),
                F("people_evt_worker_change", "property", "frappe_hr", "Salary Structure Assignment", ["base", "variable", "grade"], "emit base, variable, and/or grade rows", False, "text", "from_date", "SOURCE_NATIVE", "Comp attribute changed."),
            ],
        ),
        "frappe_appraisal.yml": file_doc(
            "appraisal",
            "Appraisal has no business status field. Canonical status is Frappe docstatus. Cycle status is SOURCE_NATIVE.",
            {"pin": ["doctypes/appraisal.json", "doctypes/appraisal_cycle.json"]},
            [
                F("people_dim_appraisal_cycle", "cycle_id", "frappe_hr", "Appraisal Cycle", "name", "identity", False, "text", "start_date", "CANONICAL_KEY", "Appraisal Cycle.name (autoname cycle_name)."),
                F("people_dim_appraisal_cycle", "cycle_name", "frappe_hr", "Appraisal Cycle", "cycle_name", "identity", False, "text", "start_date", "SOURCE_NATIVE", "Cycle label."),
                F("people_dim_appraisal_cycle", "start_date", "frappe_hr", "Appraisal Cycle", "start_date", "identity", False, "date", "start_date", "SOURCE_NATIVE", "Cycle start."),
                F("people_dim_appraisal_cycle", "end_date", "frappe_hr", "Appraisal Cycle", "end_date", "identity", False, "date", "end_date", "SOURCE_NATIVE", "Cycle end."),
                F("people_dim_appraisal_cycle", "status", "frappe_hr", "Appraisal Cycle", "status", "identity", True, "text", "start_date", "SOURCE_NATIVE", "Not Started | In Progress | Completed."),
                F("people_fact_appraisal", "appraisal_id", "frappe_hr", "Appraisal", "name", "identity", False, "text", "end_date", "CANONICAL_KEY", "Appraisal.name."),
                F("people_fact_appraisal", "worker_id", "frappe_hr", "Appraisal", "employee", "identity", False, "text", "end_date", "SOURCE_NATIVE", "Employee.link."),
                F("people_fact_appraisal", "cycle_id", "frappe_hr", "Appraisal", "appraisal_cycle", "identity", False, "text", "end_date", "SOURCE_NATIVE", "Appraisal Cycle link."),
                F("people_fact_appraisal", "final_score", "frappe_hr", "Appraisal", "final_score", "identity", True, "numeric", "end_date", "SOURCE_NATIVE", "Final score."),
                F("people_fact_appraisal", "total_score", "frappe_hr", "Appraisal", "total_score", "identity", True, "numeric", "end_date", "SOURCE_NATIVE", "Total goal score."),
                F("people_fact_appraisal", "self_score", "frappe_hr", "Appraisal", "self_score", "identity", True, "numeric", "end_date", "SOURCE_NATIVE", "Self score."),
                F("people_fact_appraisal", "status", "frappe_hr", "Appraisal", "docstatus", "0=draft 1=submitted 2=cancelled; Appraisal.json has no business status", False, "text", "modified", "SOURCE_NATIVE", "Frappe docstatus, not a business workflow field."),
                F("people_fact_appraisal", "submitted_at", "frappe_hr", "Appraisal", "modified", "modified when docstatus=1", True, "timestamptz", "modified", "DERIVED", "Submit timestamp."),
            ],
        ),
        "frappe_training.yml": file_doc(
            "training",
            "Participation grain is Training Event Employee + Training Result Employee. Hours/grade live on the result child, not the event child.",
            {"pin": ["doctypes/training_event.json", "doctypes/training_event_employee.json", "doctypes/training_result.json", "doctypes/training_result_employee.json"]},
            [
                F("people_dim_learning_resource", "resource_id", "frappe_hr", "Training Event", "name", "identity", False, "text", "start_time", "CANONICAL_KEY", "Internal resource = Training Event.name."),
                F("people_dim_learning_resource", "source", "frappe_hr", "Training Event", None, "literal internal", False, "text", "start_time", "CANONICAL_KEY", "internal vs microsoft_learn."),
                F("people_dim_learning_resource", "title", "frappe_hr", "Training Event", "event_name", "identity", False, "text", "start_time", "SOURCE_NATIVE", "Event name."),
                F("people_dim_learning_resource", "url", "frappe_hr", "Training Event", None, "null for internal events", True, "text", "start_time", "SOURCE_GAP", "Training Event has no URL field."),
                F("people_dim_learning_resource", "level", "frappe_hr", "Training Event", "level", "identity", True, "text", "start_time", "SOURCE_NATIVE", "Beginner | Intermediate | Advance."),
                F("people_dim_learning_resource", "duration_minutes", "frappe_hr", "Training Event", ["start_time", "end_time"], "extract(epoch from end_time-start_time)/60", True, "integer", "start_time", "DERIVED", "Duration from event window. Not a native minutes field."),
                F("people_dim_learning_resource", "roles", "frappe_hr", "Training Event", None, "null; no roles[] on Training Event", True, "text[]", "start_time", "SOURCE_GAP", "No roles array on the DocType."),
                F("people_dim_learning_resource", "products", "frappe_hr", "Training Event", "course", "wrap course as a one-element array when present", True, "text[]", "start_time", "DERIVED", "Course name as product tag."),
                F("people_fact_training_participation", "worker_id", "frappe_hr", "Training Event Employee", "employee", "identity", False, "text", "event_start", "SOURCE_NESTED", "Employee on the event child."),
                F("people_fact_training_participation", "training_event_id", "frappe_hr", "Training Event", "name", "parent of Training Event Employee", False, "text", "start_time", "SOURCE_NATIVE", "Training Event.name."),
                F("people_fact_training_participation", "resource_id", "frappe_hr", "Training Event", "name", "same as training_event_id for internal events", False, "text", "start_time", "CANONICAL_KEY", "Learning resource key."),
                F("people_fact_training_participation", "attendance", "frappe_hr", "Training Event Employee", "attendance", "identity", True, "text", "start_time", "SOURCE_NESTED", "Present | Absent."),
                F("people_fact_training_participation", "status", "frappe_hr", "Training Event Employee", "status", "identity", True, "text", "start_time", "SOURCE_NESTED", "Open | Invited | Completed | Feedback Submitted."),
                F("people_fact_training_participation", "hours", "frappe_hr", "Training Result Employee", "hours", "join result child on employee + training_event", True, "numeric", "end_time", "SOURCE_NESTED", "Hours from Training Result Employee."),
                F("people_fact_training_participation", "grade", "frappe_hr", "Training Result Employee", "grade", "join result child on employee + training_event", True, "text", "end_time", "SOURCE_NESTED", "Grade from Training Result Employee."),
                F("people_fact_training_participation", "event_start", "frappe_hr", "Training Event", "start_time", "identity", False, "timestamptz", "start_time", "SOURCE_NATIVE", "Event start."),
            ],
        ),
        "frappe_skill.yml": file_doc(
            "skills",
            "Proficiency is a Frappe Rating on Employee Skill. O*NET importance is the job-target, not the worker rating.",
            {"pin": ["doctypes/employee_skill_map.json", "doctypes/employee_skill.json", "doctypes/skill.json"]},
            [
                F("people_dim_skill", "skill_id", "frappe_hr", "Skill", "name", "identity", False, "text", "current", "CANONICAL_KEY", "Skill.name."),
                F("people_dim_skill", "skill_name", "frappe_hr", "Skill", "skill_name", "identity", False, "text", "current", "SOURCE_NATIVE", "Skill label."),
                F("people_dim_skill", "onet_element_id", "onet", "Essential Skills.txt", "Element ID", "via people_xw_skill", True, "text", "current", "CANONICAL_KEY", "O*NET element."),
                F("people_dim_skill", "element_type", "onet", "Essential Skills.txt", None, "Skills | Knowledge | Technology Skills from the O*NET file of origin", True, "text", "current", "SOURCE_NATIVE", "O*NET element type."),
                F("people_fact_worker_skill", "worker_id", "frappe_hr", "Employee Skill Map", "employee", "identity", False, "text", "evaluation_date", "SOURCE_NATIVE", "Employee on the skill map."),
                F("people_fact_worker_skill", "skill_id", "frappe_hr", "Employee Skill", "skill", "identity", False, "text", "evaluation_date", "SOURCE_NESTED", "Skill link."),
                F("people_fact_worker_skill", "proficiency", "frappe_hr", "Employee Skill", "proficiency", "Frappe Rating 0-1 scaled to 1-5: round(proficiency*5) with floor 1", False, "integer", "evaluation_date", "SOURCE_NESTED", "Worker proficiency 1-5."),
                F("people_fact_worker_skill", "evaluation_date", "frappe_hr", "Employee Skill", "evaluation_date", "identity", True, "date", "evaluation_date", "SOURCE_NESTED", "Evaluation date."),
                F("people_fact_worker_skill", "source_skill_map", "frappe_hr", "Employee Skill Map", "name", "identity", False, "text", "evaluation_date", "SOURCE_NATIVE", "Parent Employee Skill Map.name."),
                F("people_ref_job_skill_target", "job_id", "frappe_hr", "Designation", "name", "via people_xw_job", False, "text", "current", "CANONICAL_KEY", "Job for the target."),
                F("people_ref_job_skill_target", "skill_id", "onet", "Essential Skills.txt", "Element ID", "via people_xw_skill", False, "text", "current", "CANONICAL_KEY", "Skill for the target."),
                F("people_ref_job_skill_target", "target_proficiency", "onet", "Essential Skills.txt", "Importance", "scale O*NET importance 1-5 (BR-SK-001)", True, "integer", "current", "DERIVED", "Target proficiency from O*NET importance."),
                F("people_ref_job_skill_target", "onet_importance", "onet", "Essential Skills.txt", "Importance", "identity", True, "numeric", "current", "SOURCE_NATIVE", "O*NET importance."),
            ],
        ),
        "people_hist_worker_attr.yml": file_doc(
            "hist",
            "As-of history is rebuilt from hire initial state + people_evt_worker + people_evt_worker_change. Not stored in a source object.",
            {"rules": "BR-WF-008"},
            [
                F("people_hist_worker_attr", "worker_id", "canonical", "people_evt_worker", "worker_id", "identity from event stream (BR-WF-008)", False, "text", "valid_from", "CANONICAL_KEY", "Worker of the interval."),
                F("people_hist_worker_attr", "valid_from", "canonical", "people_evt_worker", "event_date", "interval start; first interval valid_from = hire_date (BR-WF-008)", False, "date", "valid_from", "DERIVED", "Inclusive start. Seamlessly covers hire_date."),
                F("people_hist_worker_attr", "valid_to", "canonical", "people_evt_worker", "event_date", "next event_date or 9999-12-31; intervals do not overlap (BR-WF-008)", True, "date", "valid_to", "DERIVED", "Exclusive end."),
                F("people_hist_worker_attr", "org_id", "frappe_hr", "Employee", "department", "as-of from hire snapshot + property history department (BR-WF-008)", True, "text", "valid_from", "DERIVED", "Org as-of."),
                F("people_hist_worker_attr", "job_id", "frappe_hr", "Employee", "designation", "as-of from hire snapshot + property history designation (BR-WF-008)", True, "text", "valid_from", "DERIVED", "Job as-of."),
                F("people_hist_worker_attr", "grade_id", "frappe_hr", "Employee", "grade", "as-of from hire snapshot + property history grade; current Employee.grade is the HRMS custom field (BR-WF-008)", True, "text", "valid_from", "DERIVED", "Grade as-of. Source field is HRMS custom field, not ERPNext Employee.json."),
                F("people_hist_worker_attr", "location_id", "frappe_hr", "Employee", "branch", "as-of from hire snapshot + property history branch (BR-WF-008)", True, "text", "valid_from", "DERIVED", "Location as-of."),
                F("people_hist_worker_attr", "manager_worker_id", "frappe_hr", "Employee", "reports_to", "as-of from hire snapshot + property history reports_to (BR-WF-008)", True, "text", "valid_from", "DERIVED", "Manager worker as-of."),
                F("people_hist_worker_attr", "employment_type", "frappe_hr", "Employee", "employment_type", "as-of from hire snapshot + property history employment_type (BR-WF-008)", True, "text", "valid_from", "SOURCE_NATIVE", "HRMS custom field. Same Link as people_dim_worker.employment_type."),
                F("people_hist_worker_attr", "status", "frappe_hr", "Employee", "status", "as-of Active/Inactive/Suspended/Left (BR-WF-008)", False, "text", "valid_from", "DERIVED", "Employment status as-of."),
                F("people_hist_worker_attr", "source_event_id", "canonical", "people_evt_worker", "event_id", "event that opened this interval (BR-WF-008)", False, "text", "valid_from", "CANONICAL_KEY", "Provenance event."),
            ],
        ),
        "people_dim_date.yml": file_doc(
            "date",
            "Generated calendar. Not sourced from HRIS or ATS.",
            {"rules": "calendar"},
            [
                F("people_dim_date", "date", "canonical", "people_dim_date", None, "generate date spine covering backfill through today", False, "date", "date", "CANONICAL_KEY", "Calendar date."),
                F("people_dim_date", "month_end", "canonical", "people_dim_date", "date", "last day of month containing date", False, "date", "date", "DERIVED", "Month-end of this date."),
                F("people_dim_date", "is_month_end", "canonical", "people_dim_date", "date", "date = month_end", False, "boolean", "date", "DERIVED", "True on month-end rows."),
            ],
        ),
    }


def main() -> int:
    for name, payload in mappings().items():
        dump(ROOT / name, payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
