from __future__ import annotations

"""Write v1 metric YAML files matching architecture §8 (6c definitions)."""

from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parents[1] / "people_metrics"

# id, file, grain, num, den, min_cell, sensitivity, window, annualized, range, sources, window_aligned, extra
METRICS = [
    dict(
        metric_id="headcount",
        file="headcount.yml",
        grain="people_snap_worker_month",
        numerator="count(is_certified) as-of month_end",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="as_of",
        annualized=False,
        expected_range=[40000, 60000],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="average_headcount",
        file="average_headcount.yml",
        grain="people_snap_worker_month",
        numerator="mean of month-end certified headcount",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[30000, 55000],
        sources=["people_snap_worker_month"],
        notes="Default trailing-12m month-end certified mean. grain=month returns that month's certified HC. Attrition denominators reference this metric.",
    ),
    dict(
        metric_id="hires",
        file="hires.yml",
        grain="people_snap_worker_month",
        numerator="certified hired_in_month ∧ via_t1 ∧ not is_rehire",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[5000, 25000],
        sources=["people_snap_worker_month"],
        notes="External hires only. hires_total = hires + rehires (derived, not a separate RPC).",
    ),
    dict(
        metric_id="rehires",
        file="rehires.yml",
        grain="people_snap_worker_month",
        numerator="certified hired_in_month ∧ is_rehire",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[0, 3000],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="voluntary_attrition_rate",
        file="voluntary_attrition.yml",
        grain="people_snap_worker_month",
        numerator="terminated_in_month ∧ voluntary (sum over window)",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.08, 0.22],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="involuntary_attrition_rate",
        file="involuntary_attrition.yml",
        grain="people_snap_worker_month",
        numerator="terminated_in_month ∧ involuntary (sum over window)",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.01, 0.10],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="regrettable_attrition_rate",
        file="regrettable_attrition.yml",
        grain="people_snap_worker_month",
        numerator="is_regrettable (sum over window)",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="confidential",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.00, 0.12],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="promotion_rate",
        file="promotion_rate.yml",
        grain="people_snap_worker_month",
        numerator="promoted_in_month ∧ is_certified (sum over window)",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.04, 0.14],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="internal_mobility_rate",
        file="internal_mobility.yml",
        grain="people_snap_worker_month",
        numerator="transferred_in_month ∧ is_certified (sum over window)",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.02, 0.20],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="manager_turnover_rate",
        file="manager_turnover.yml",
        grain="people_snap_worker_month",
        numerator="terminated_in_month and (is_manager or was manager in the prior month)",
        denominator="trailing-12m mean of certified managers",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=True,
        expected_range=[0.02, 0.25],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="span_of_control",
        file="span_of_control.yml",
        grain="people_snap_worker_month",
        numerator="avg(direct_report_count) among is_manager ∧ is_certified",
        denominator="managers",
        min_cell=5,
        sensitivity="internal",
        time_logic="as_of",
        annualized=False,
        expected_range=[4, 12],
        sources=["people_snap_worker_month"],
    ),
    dict(
        metric_id="time_to_fill_days",
        file="time_to_fill.yml",
        grain="people_dim_requisition",
        numerator="median(closed_at - opened_at) where close_reason=hired",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[10, 90],
        sources=["people_dim_requisition"],
    ),
    dict(
        metric_id="time_in_stage_hours",
        file="time_in_stage.yml",
        grain="people_evt_application_stage",
        numerator="median hours in each canonical_stage and overall (exited-entered; open stages use entered as both ends)",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[24, 2000],
        sources=["people_evt_application_stage"],
        window_aligned=True,
        notes="RPC value is the overall median; payload.by_stage has Review/Screen/Onsite/Offer medians. Window is entered_at in trailing-12m (aligned to the published hot window).",
    ),
    dict(
        metric_id="offer_acceptance_rate",
        file="offer_acceptance.yml",
        grain="people_fact_offer",
        numerator="accepted / (accepted+rejected) in window",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[0.50, 0.95],
        sources=["people_fact_offer"],
    ),
    dict(
        metric_id="applications_per_opening",
        file="applications_per_opening.yml",
        grain="people_fact_application",
        numerator="applications with applied_at in trailing-12m / requisitions with opened_at in the same window",
        denominator=None,
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[60, 250],
        sources=["people_fact_application", "people_dim_requisition"],
        window_aligned=True,
        notes="BR-DQ-005: numerator and denominator share the trailing-12m window (applied_at and opened_at).",
    ),
    dict(
        metric_id="quality_of_hire",
        file="quality_of_hire.yml",
        grain="people_snap_worker_month",
        numerator="still certified at as_of AND first appraisal final_score ≥ 3.5",
        denominator="via_t1 hires whose hire_date is in (as_of-24m, as_of-12m] (12-month retention window has closed)",
        min_cell=10,
        sensitivity="confidential",
        time_logic="as_of",
        annualized=False,
        expected_range=[0.15, 0.85],
        sources=["people_snap_worker_month", "people_fact_appraisal"],
        notes="Composition: 12-month retention × first final_score ≥ 3.5. Missing first appraisal fails the score clause.",
    ),
    dict(
        metric_id="recruiter_load",
        file="recruiter_load.yml",
        grain="people_snap_recruiter_month",
        numerator="avg(open_requisitions) at as_of month (is_open × recruiter_id)",
        denominator="recruiters",
        min_cell=3,
        sensitivity="internal",
        time_logic="as_of",
        annualized=False,
        expected_range=[0.5, 20],
        sources=["people_snap_recruiter_month"],
    ),
    dict(
        metric_id="compa_ratio_median",
        file="compa_ratio.yml",
        grain="people_fact_comp_assignment_restricted",
        numerator="median(base / band_mid) for certified workers as-of",
        denominator=None,
        min_cell=10,
        sensitivity="restricted",
        time_logic="as_of",
        annualized=False,
        expected_range=[0.70, 1.30],
        sources=["people_fact_comp_assignment_restricted", "people_ref_comp_band"],
    ),
    dict(
        metric_id="engagement_score",
        file="engagement_score.yml",
        grain="people_fact_survey_score_restricted",
        numerator="mean(score_mean)",
        denominator=None,
        min_cell=5,
        sensitivity="confidential",
        time_logic="as_of",
        annualized=False,
        expected_range=[2.5, 4.5],
        sources=["people_fact_survey_score_restricted"],
    ),
    dict(
        metric_id="training_hours_per_worker",
        file="training_hours.yml",
        grain="people_mart_learning_monthly",
        numerator="sum(training_hours) over trailing-12m",
        denominator="average_headcount",
        min_cell=5,
        sensitivity="internal",
        time_logic="trailing_12m",
        annualized=False,
        expected_range=[1, 40],
        sources=["people_mart_learning_monthly"],
    ),
    dict(
        metric_id="skill_coverage",
        file="skill_coverage.yml",
        grain="people_mart_skill_coverage_monthly",
        numerator="mean over workers of (held target skills meeting coalesce(target_proficiency, 3) / n_target)",
        denominator="certified workers whose job_id has at least one people_ref_job_skill_target row",
        min_cell=5,
        sensitivity="internal",
        time_logic="as_of",
        annualized=False,
        expected_range=[0.3, 0.95],
        sources=["people_mart_skill_coverage_monthly", "people_ref_job_skill_target", "people_fact_worker_skill"],
        notes="Workers with no target skills are excluded from the denominator. Empty target_proficiency coalesces to 3.",
    ),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for row in METRICS:
        body = {
            "metric_id": row["metric_id"],
            "status": "certified",
            "grain": row["grain"],
            "architecture": "docs/PEOPLE_DATA_ARCHITECTURE.md#8",
            "time_logic": row["time_logic"],
            "annualized": row["annualized"],
            "numerator": {"expression": row["numerator"]},
            "min_cell": row["min_cell"],
            "sensitivity": row["sensitivity"],
            "expected_range": row["expected_range"],
            "sources": row["sources"],
            "window_aligned": bool(row.get("window_aligned", False)),
            "sandbox": {"rule_kind": "parametric", "rpc": "people_v2.people_get_metric"},
        }
        if row.get("denominator"):
            body["denominator"] = {"expression": row["denominator"]}
        if row.get("notes"):
            body["notes"] = row["notes"]
        (OUT / row["file"]).write_text(yaml.safe_dump(body, sort_keys=False, allow_unicode=True), encoding="utf-8")
        print("wrote", row["file"])


if __name__ == "__main__":
    main()
