import type { CatalogItem, StrategyCategory, StrategyIntent } from "@/types/strategy";

type CatalogRow = [
  id: string,
  kind: StrategyIntent,
  category: StrategyCategory,
  title: string,
  statement: string,
  source: string,
  sourceUrl: string,
  metricIds: string[],
  population?: string,
];

const rows: CatalogRow[] = [
  [
    "ta-speed-01",
    "strategy",
    "Talent Acquisition",
    "Reduce Time to Fill for priority AI and Engineering roles",
    "Reduce median Time to Fill for priority AI and Engineering roles from the current baseline to 45 days, while holding Quality of Hire and offer acceptance steady.",
    "Gartner 2026 CHRO Priorities — now-next talent strategy",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["time_to_fill", "quality_of_hire", "offer_acceptance", "interview_scheduling", "candidate_satisfaction"],
    "AI + Engineering",
  ],
  [
    "ta-qoh-01",
    "strategy",
    "Talent Acquisition",
    "Raise Quality of Hire without slowing critical requisitions",
    "Improve first-year Quality of Hire for priority roles while keeping Time to Fill inside the approved range.",
    "SHRM / ISO 30414 human-capital reporting practice",
    "https://www.iso.org/standard/69338.html",
    ["quality_of_hire", "time_to_fill", "hiring_manager_satisfaction", "first_year_attrition"],
    "Priority professional roles",
  ],
  [
    "ta-skills-source-01",
    "strategy",
    "Talent Acquisition",
    "Build a skills-based sourcing plan for scarce digital talent",
    "Shift sourcing from job-title matching to critical-skill coverage so scarce digital capabilities are hired or borrowed with less channel concentration.",
    "Deloitte 2025–26 workforce planning — skills over static roles",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["skills_coverage", "source_effectiveness", "time_to_first_qualified", "cost_per_hire"],
    "Digital and data roles",
  ],
  [
    "ta-offer-01",
    "strategy",
    "Talent Acquisition",
    "Increase offer acceptance for competitive technical roles",
    "Raise offer acceptance by shortening approval time and making the candidate experience consistent through offer close.",
    "LinkedIn Talent / recruiting operations practice",
    "https://www.linkedin.com/business/talent/blog",
    ["offer_acceptance", "offer_approval", "candidate_satisfaction", "time_to_fill"],
    "Competitive technical roles",
  ],
  [
    "ta-cost-01",
    "strategy",
    "Talent Acquisition",
    "Lower cost per hire while protecting candidate experience",
    "Reduce cost per hire by improving source mix and internal fill, without lowering candidate satisfaction.",
    "CIPD resourcing and talent planning guidance",
    "https://www.cipd.org/en/knowledge/factsheets/resourcing-talent-factsheet/",
    ["cost_per_hire", "internal_fill", "source_effectiveness", "candidate_satisfaction"],
  ],
  [
    "ta-human-ai-01",
    "strategy",
    "Talent Acquisition",
    "Create a now-next hiring plan for human-AI blended teams",
    "Plan hiring for work that will be shared with AI systems: hire judgment and process skill, not only tool certificates.",
    "Gartner 2026 — shape work in the human-machine era",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["skills_coverage", "time_to_fill", "quality_of_hire", "ai_adoption"],
    "AI-enabled teams",
  ],
  [
    "ta-internal-first-01",
    "strategy",
    "Talent Acquisition",
    "Make internal candidates the first slate for priority reqs",
    "Require an internal slate before external spend on designated requisitions, and measure internal fill as an outcome.",
    "Josh Bersin skills-based organization research",
    "https://joshbersin.com/",
    ["internal_fill", "time_to_fill", "internal_mobility", "hiring_manager_satisfaction"],
  ],
  [
    "ta-prob-ttf-01",
    "problem",
    "Talent Acquisition",
    "Time to Fill for critical roles is missing the target",
    "Median Time to Fill on critical requisitions is above the approved target, and leaders cannot see which stage is responsible.",
    "Common TA operating problem; metric standard from ISO 30414-style cycle time",
    "https://www.iso.org/standard/69338.html",
    ["time_to_fill", "interview_scheduling", "offer_approval", "requisition_aging"],
    "Critical roles",
  ],
  [
    "ta-prob-schedule-01",
    "problem",
    "Talent Acquisition",
    "Interview scheduling is the longest hiring stage",
    "Interview scheduling consumes more calendar time than screening or offer close, especially for multi-interviewer loops.",
    "Recruiting operations bottleneck pattern",
    "https://www.cipd.org/en/knowledge/factsheets/resourcing-talent-factsheet/",
    ["interview_scheduling", "time_to_fill", "candidate_satisfaction"],
  ],
  [
    "ta-prob-offer-01",
    "problem",
    "Talent Acquisition",
    "Offer approval delays are losing candidates",
    "Candidates drop after verbal interest because written offer approval takes longer than the competing offer cycle.",
    "TA process risk documented in recruiting operations practice",
    "https://www.linkedin.com/business/talent/blog",
    ["offer_approval", "offer_acceptance", "time_to_fill"],
  ],
  [
    "ta-prob-quality-01",
    "problem",
    "Talent Acquisition",
    "Hiring volume is high but first-year quality is weak",
    "The team is filling seats, yet first-year performance and retention are below the Quality of Hire standard.",
    "Quality of Hire practice (SHRM / ISO 30414)",
    "https://www.shrm.org/",
    ["quality_of_hire", "first_year_attrition", "hiring_manager_satisfaction", "time_to_hire"],
  ],
  [
    "ta-prob-aging-01",
    "problem",
    "Talent Acquisition",
    "Requisitions age past 60 days with no owner",
    "A material share of open requisitions are older than 60 days and no longer have an active hiring-manager owner.",
    "Requisition hygiene / aging SLA practice",
    "https://www.cipd.org/en/knowledge/factsheets/resourcing-talent-factsheet/",
    ["requisition_aging", "time_to_fill", "hiring_manager_satisfaction"],
  ],
  [
    "ta-prob-cx-01",
    "problem",
    "Talent Acquisition",
    "Candidate experience drops after onsite interviews",
    "Candidate satisfaction is acceptable at apply and screen, then falls after onsite or panel stages.",
    "Candidate experience research practice",
    "https://www.linkedin.com/business/talent/blog",
    ["candidate_satisfaction", "interview_scheduling", "offer_acceptance"],
  ],
  [
    "ta-prob-source-01",
    "problem",
    "Talent Acquisition",
    "Pipelines depend on one recruiting channel",
    "More than half of hires come from a single source, so volume and quality move together when that channel changes.",
    "Source-of-hire concentration risk",
    "https://www.cipd.org/en/knowledge/factsheets/resourcing-talent-factsheet/",
    ["source_effectiveness", "cost_per_hire", "quality_of_hire"],
  ],
  [
    "ta-prob-slate-01",
    "problem",
    "Talent Acquisition",
    "Hiring managers reject slates late in the process",
    "Managers accept a req, then reject the slate after interviews, restarting Time to Fill.",
    "Intake and slate-quality operating problem",
    "https://www.shrm.org/",
    ["hiring_manager_satisfaction", "time_to_first_qualified", "time_to_fill"],
  ],
  [
    "ret-fy-01",
    "strategy",
    "Retention",
    "Reduce first-year regrettable attrition",
    "Cut first-year regrettable exits by improving role match, manager support, and onboarding milestones.",
    "Gallup / CIPD retention and onboarding practice",
    "https://www.gallup.com/workplace/",
    ["first_year_attrition", "regrettable_attrition", "quality_of_hire", "manager_effectiveness"],
    "New hires · first 12 months",
  ],
  [
    "ret-critical-01",
    "strategy",
    "Retention",
    "Retain employees in critical skills and roles",
    "Hold retention of designated critical-skill employees above the approved threshold while monitoring pay and mobility.",
    "Deloitte workforce planning — retain scarce capability",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["retention_critical", "regrettable_attrition", "internal_mobility", "compa_ratio"],
    "Critical-skill population",
  ],
  [
    "ret-manager-01",
    "strategy",
    "Retention",
    "Make managers the primary retention system",
    "Improve manager effectiveness and stay-interview completion so retention actions happen before an exit interview.",
    "SHRM 2026 — leadership and manager development is a top CHRO priority",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["manager_effectiveness", "regrettable_attrition", "engagement_index"],
  ],
  [
    "ret-stay-01",
    "strategy",
    "Retention",
    "Build stay interviews into the operating rhythm",
    "Run structured stay interviews for critical roles each quarter and track whether identified risks are closed.",
    "CIPD employee retention practice",
    "https://www.cipd.org/en/knowledge/factsheets/employee-turnover-retention-factsheet/",
    ["retention_critical", "manager_effectiveness", "enps"],
  ],
  [
    "ret-prob-fy-01",
    "problem",
    "Retention",
    "First-year attrition is rising",
    "A rising share of new hires leave before 12 months, and the team cannot separate poor match from onboarding failure.",
    "Onboarding and early attrition pattern",
    "https://www.cipd.org/en/knowledge/factsheets/employee-turnover-retention-factsheet/",
    ["first_year_attrition", "quality_of_hire", "time_to_productivity"],
  ],
  [
    "ret-prob-hp-01",
    "problem",
    "Retention",
    "High performers leave shortly after promotion",
    "Employees rated high performing exit within a year of promotion, suggesting the next role or manager support is failing.",
    "High-performer retention risk",
    "https://www.gallup.com/workplace/",
    ["high_performer_retention", "promotion_rate", "manager_effectiveness"],
  ],
  [
    "ret-prob-cluster-01",
    "problem",
    "Retention",
    "Exits are clustered in one organization or location",
    "Attrition is not uniform. One unit or location accounts for a disproportionate share of voluntary exits.",
    "Workforce planning signal monitoring (Deloitte)",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/autonomous-workforce-planning.html",
    ["overall_attrition", "regrettable_attrition", "engagement_index"],
  ],
  [
    "ret-prob-exit-01",
    "problem",
    "Retention",
    "Exit reasons are incomplete or unused",
    "Exit data is missing, coded too coarsely, or never compared with stay-interview themes.",
    "People analytics evidence-gap pattern",
    "https://www.cipd.org/en/knowledge/factsheets/people-analytics-factsheet/",
    ["data_completeness", "regrettable_attrition", "overall_attrition"],
  ],
  [
    "ret-prob-regret-01",
    "problem",
    "Retention",
    "New-hire regret is visible in early pulses",
    "New hires report low role clarity or manager support in the first 90 days, ahead of actual exits.",
    "Early-tenure experience practice",
    "https://www.gallup.com/workplace/",
    ["first_year_attrition", "manager_effectiveness", "engagement_index"],
  ],
  [
    "ret-prob-mgr-change-01",
    "problem",
    "Retention",
    "Manager changes line up with later exits",
    "Teams that change manager show higher attrition in the following two quarters.",
    "Manager stability and retention research practice",
    "https://www.shrm.org/",
    ["manager_effectiveness", "overall_attrition", "span_of_control"],
  ],
  [
    "ret-prob-comp-story-01",
    "problem",
    "Retention",
    "Comp is cited in exits, but career path is the real driver",
    "Exit comments mention pay, yet internal mobility and promotion timing explain more of the pattern.",
    "CIPD turnover drivers practice",
    "https://www.cipd.org/en/knowledge/factsheets/employee-turnover-retention-factsheet/",
    ["internal_mobility", "promotion_rate", "compa_ratio", "regrettable_attrition"],
  ],
  [
    "ret-prob-alumni-01",
    "problem",
    "Retention",
    "Alumni rehire is available but unused",
    "Former employees in good standing are not a measured source, so the company re-buys the same skills externally.",
    "Boomerang hiring practice",
    "https://www.linkedin.com/business/talent/blog",
    ["source_effectiveness", "cost_per_hire", "time_to_productivity"],
  ],
  [
    "sk-gap-01",
    "strategy",
    "Skills & Capability",
    "Close critical skill gaps for AI-enabled work",
    "Identify the five skills that constrain the AI roadmap and close coverage through build, buy, borrow, or bot.",
    "Gartner 2026 — HR-focused AI strategy and blended workforce",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["skills_coverage", "critical_skill_gap", "learning_hours", "internal_fill"],
    "AI-enabled work",
  ],
  [
    "sk-swo-01",
    "strategy",
    "Skills & Capability",
    "Move from job-based to skills-based workforce planning",
    "Plan supply and demand on skills and work outcomes, not only headcount by job title.",
    "Deloitte — reinventing workforce planning",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["skills_coverage", "headcount_vs_plan", "internal_mobility", "contractor_ratio"],
  ],
  [
    "sk-academy-01",
    "strategy",
    "Skills & Capability",
    "Build internal academies for the scarcest skills",
    "Stand up targeted academies so learning hours convert to verified proficiency, not attendance.",
    "LinkedIn Workplace Learning / skills-based org practice",
    "https://learning.linkedin.com/resources/workplace-learning-report",
    ["skills_coverage", "learning_hours", "internal_fill", "time_to_productivity"],
  ],
  [
    "sk-ai-collab-01",
    "strategy",
    "Skills & Capability",
    "Raise proficiency in human-AI collaboration",
    "Train targeted roles to use approved AI tools with judgment and process skill, and measure active use plus quality guardrails.",
    "Gartner 2026 AI in HR / human-machine work",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["ai_adoption", "skills_coverage", "quality_of_hire", "wellbeing_index"],
  ],
  [
    "sk-prob-inventory-01",
    "problem",
    "Skills & Capability",
    "The skills inventory is outdated or self-rated only",
    "Skill data is stale or only self-reported, so coverage numbers cannot support a build/buy decision.",
    "Skills intelligence evidence gap",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["data_completeness", "skills_coverage", "critical_skill_gap"],
  ],
  [
    "sk-prob-cover-01",
    "problem",
    "Skills & Capability",
    "Critical skill coverage is below plan",
    "Named critical skills have fewer proficient people than the demand plan, and hiring is not closing the gap fast enough.",
    "Deloitte / Gartner SWP confidence gap",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["skills_coverage", "critical_skill_gap", "time_to_fill"],
  ],
  [
    "sk-prob-hours-01",
    "problem",
    "Skills & Capability",
    "Learning hours do not convert to proficiency",
    "Employees complete courses, but proficiency assessments and internal fill for those skills do not move.",
    "Learning transfer problem",
    "https://learning.linkedin.com/resources/workplace-learning-report",
    ["learning_hours", "skills_coverage", "internal_fill"],
  ],
  [
    "sk-prob-buy-01",
    "problem",
    "Skills & Capability",
    "The company buys skills it already employs",
    "External hiring continues for capabilities that exist internally but are not visible or movable.",
    "Internal talent marketplace failure mode",
    "https://joshbersin.com/",
    ["internal_fill", "skills_coverage", "cost_per_hire"],
  ],
  [
    "sk-prob-ai-quality-01",
    "problem",
    "Skills & Capability",
    "AI tools are adopted but output quality is unchecked",
    "License counts look healthy, yet leaders see low-quality AI-assisted work and rising rework.",
    "Gartner-related 2026 quality-vs-speed risk",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["ai_adoption", "quality_of_hire", "wellbeing_index"],
  ],
  [
    "sk-prob-map-01",
    "problem",
    "Skills & Capability",
    "Capability maps are not linked to demand",
    "HR has a capability model, Finance has a headcount plan, and neither shares an as-of date or skill list.",
    "Deloitte SWP integration gap",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["headcount_vs_plan", "skills_coverage", "data_completeness"],
  ],
  [
    "sk-prob-cert-01",
    "problem",
    "Skills & Capability",
    "Certificates are treated as proficiency",
    "Completion badges are used as skill evidence, so coverage is overstated.",
    "Skills measurement standard problem",
    "https://www.cipd.org/en/knowledge/factsheets/learning-development-strategy-factsheet/",
    ["skills_coverage", "learning_hours", "data_completeness"],
  ],
  [
    "sk-prob-vendor-01",
    "problem",
    "Skills & Capability",
    "Vendor skills sit outside the inventory",
    "Contractors and partners hold critical skills that never appear in internal coverage.",
    "Blended workforce visibility gap",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["contractor_ratio", "skills_coverage", "critical_skill_gap"],
  ],
  [
    "ld-mgr-01",
    "strategy",
    "Leadership",
    "Strengthen frontline manager effectiveness",
    "Raise manager effectiveness scores and reduce team-level attrition where manager quality is the constraint.",
    "SHRM 2026 CHRO Priorities — leadership and manager development",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["manager_effectiveness", "engagement_index", "regrettable_attrition"],
    "People managers",
  ],
  [
    "ld-change-01",
    "strategy",
    "Leadership",
    "Mobilize leaders to routinize change",
    "Equip managers to make change a habit of work, not a campaign, so adoption holds after the launch period.",
    "Gartner 2026 — mobilize leaders for growth in uncertainty",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["change_adoption", "manager_effectiveness", "engagement_index"],
  ],
  [
    "ld-succession-01",
    "strategy",
    "Leadership",
    "Build succession depth for critical roles",
    "Ensure every critical role has a documented ready-now or ready-in-one-year successor.",
    "CIPD succession planning practice",
    "https://www.cipd.org/en/knowledge/factsheets/succession-planning-factsheet/",
    ["bench_strength", "succession_readiness", "retention_critical"],
    "Critical leadership roles",
  ],
  [
    "ld-first-line-01",
    "strategy",
    "Leadership",
    "Improve first-time manager success",
    "Give new managers a 180-day support path and measure survival, engagement, and team attrition.",
    "SHRM manager development priority",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["manager_effectiveness", "first_year_attrition", "span_of_control"],
    "First-time managers",
  ],
  [
    "ld-prob-low-01",
    "problem",
    "Leadership",
    "Manager effectiveness scores are below the standard",
    "A large share of teams rate their manager below the approved favorable threshold.",
    "SHRM 2026 manager-development priority",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["manager_effectiveness", "engagement_index", "overall_attrition"],
  ],
  [
    "ld-prob-bench-01",
    "problem",
    "Leadership",
    "Bench strength for critical roles is thin",
    "Too many critical roles have no named successor, or the same person is listed on several benches.",
    "CIPD succession practice",
    "https://www.cipd.org/en/knowledge/factsheets/succession-planning-factsheet/",
    ["bench_strength", "succession_readiness", "retention_critical"],
  ],
  [
    "ld-prob-ftm-01",
    "problem",
    "Leadership",
    "First-time managers fail in year one",
    "New managers exit or are moved out within 12 months, and their teams show engagement drops.",
    "First-line leadership risk",
    "https://www.gallup.com/workplace/",
    ["manager_effectiveness", "first_year_attrition", "span_of_control"],
  ],
  [
    "ld-prob-fatigue-01",
    "problem",
    "Leadership",
    "Change fatigue is stalling adoption",
    "Employees report too many concurrent changes, and adoption of the current program is below plan.",
    "Gartner 2026 change-as-habit / SHRM change discipline",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["change_adoption", "wellbeing_index", "engagement_index"],
  ],
  [
    "ld-prob-span-01",
    "problem",
    "Leadership",
    "Span of control is uneven and unmanaged",
    "Some managers have very large teams while others have two reports, with no org-design rule.",
    "Organization design practice",
    "https://www.mckinsey.com/capabilities/people-and-organizational-performance",
    ["span_of_control", "manager_effectiveness", "workforce_cost"],
  ],
  [
    "ld-prob-ready-01",
    "problem",
    "Leadership",
    "Ready-now ratings are not standardized",
    "Succession labels differ by function, so bench strength cannot be compared.",
    "Succession data-standard gap",
    "https://www.cipd.org/en/knowledge/factsheets/succession-planning-factsheet/",
    ["succession_readiness", "data_completeness", "bench_strength"],
  ],
  [
    "im-fill-01",
    "strategy",
    "Internal Mobility",
    "Increase internal fill for priority roles",
    "Fill a larger share of priority requisitions from internal candidates and make exceptions visible.",
    "Skills-based internal marketplace practice",
    "https://joshbersin.com/",
    ["internal_fill", "time_to_fill", "internal_mobility", "quality_of_hire"],
  ],
  [
    "im-market-01",
    "strategy",
    "Internal Mobility",
    "Use the internal marketplace before external spend",
    "Post designated roles internally for a set window and measure conversion from visible to applied to filled.",
    "Internal talent marketplace practice",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["internal_fill", "internal_mobility", "cost_per_hire"],
  ],
  [
    "im-speed-01",
    "strategy",
    "Internal Mobility",
    "Reduce time to complete an internal move",
    "Shorten the cycle from internal apply to start date so mobility is faster than a comparable external hire.",
    "CIPD career and mobility practice",
    "https://www.cipd.org/en/knowledge/factsheets/",
    ["internal_mobility", "process_cycle_time", "time_to_productivity"],
  ],
  [
    "im-prob-external-01",
    "problem",
    "Internal Mobility",
    "Internal candidates lose to external hires by default",
    "Qualified internal applicants are passed over without a documented reason, and internal fill stays low.",
    "Internal equity of opportunity problem",
    "https://www.shrm.org/",
    ["internal_fill", "hiring_manager_satisfaction", "inclusion_index"],
  ],
  [
    "im-prob-hoard-01",
    "problem",
    "Internal Mobility",
    "Managers block internal moves",
    "Home managers delay or deny releases, so mobility policy exists on paper only.",
    "Talent hoarding operating problem",
    "https://joshbersin.com/",
    ["internal_mobility", "manager_effectiveness", "internal_fill"],
  ],
  [
    "im-prob-visibility-01",
    "problem",
    "Internal Mobility",
    "Employees cannot see adjacent roles",
    "Role architecture and postings are not visible, so employees wait for a manager to tap them.",
    "Career visibility gap",
    "https://learning.linkedin.com/resources/workplace-learning-report",
    ["internal_mobility", "engagement_index", "data_completeness"],
  ],
  [
    "im-prob-rate-01",
    "problem",
    "Internal Mobility",
    "Internal fill rate is below the approved target",
    "The company set an internal-fill goal and is missing it on the roles that matter most.",
    "Internal fill outcome miss",
    "https://www.cipd.org/en/knowledge/factsheets/",
    ["internal_fill", "time_to_fill", "source_effectiveness"],
  ],
  [
    "im-prob-gigs-01",
    "problem",
    "Internal Mobility",
    "Internal gigs are activity, not capability building",
    "Short projects are counted as mobility, but they do not change proficiency or succession readiness.",
    "Mobility quality problem",
    "https://joshbersin.com/",
    ["internal_mobility", "skills_coverage", "bench_strength"],
  ],
  [
    "ec-culture-01",
    "strategy",
    "Engagement & Culture",
    "Embed desired culture in daily work",
    "Move culture from values posters to manager routines, recognition, and decision rights that show up in performance.",
    "Gartner 2026 — address culture atrophy to power performance",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["engagement_index", "manager_effectiveness", "change_adoption"],
  ],
  [
    "ec-ex-01",
    "strategy",
    "Engagement & Culture",
    "Improve employee experience as a CHRO priority",
    "Raise experience and engagement in the moments that matter: onboarding, manager changes, and transformation.",
    "SHRM 2026 — employee experience and culture",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["engagement_index", "enps", "first_year_attrition"],
  ],
  [
    "ec-hybrid-01",
    "strategy",
    "Engagement & Culture",
    "Raise engagement in hybrid and distributed teams",
    "Close the engagement gap between on-site and hybrid teams by fixing manager rituals, not by a single return-to-office rule.",
    "Gallup workplace engagement research",
    "https://www.gallup.com/workplace/",
    ["engagement_index", "manager_effectiveness", "wellbeing_index"],
  ],
  [
    "ec-fatigue-01",
    "strategy",
    "Engagement & Culture",
    "Treat change fatigue as a measurable risk",
    "Limit concurrent programs and measure adoption, wellbeing, and engagement together.",
    "SHRM 2026 change management as operating discipline",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["change_adoption", "wellbeing_index", "engagement_index"],
  ],
  [
    "ec-prob-drop-01",
    "problem",
    "Engagement & Culture",
    "Engagement fell after a transformation",
    "Engagement or eNPS dropped in the units that absorbed the most process or AI change.",
    "SHRM / Gartner transformation side-effect",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["engagement_index", "change_adoption", "ai_adoption"],
  ],
  [
    "ec-prob-mgr-var-01",
    "problem",
    "Engagement & Culture",
    "Culture scores vary more by manager than by location",
    "The spread across managers is larger than the spread across sites, so a company-wide campaign will miss the constraint.",
    "Gallup manager-as-culture research practice",
    "https://www.gallup.com/workplace/",
    ["manager_effectiveness", "engagement_index", "span_of_control"],
  ],
  [
    "ec-prob-enps-01",
    "problem",
    "Engagement & Culture",
    "eNPS dropped in operations",
    "Operations or customer-facing units show a sharp eNPS decline while corporate scores look stable.",
    "Segmented experience problem",
    "https://www.cipd.org/en/knowledge/factsheets/employee-engagement-factsheet/",
    ["enps", "engagement_index", "overtime_rate"],
  ],
  [
    "ec-prob-action-01",
    "problem",
    "Engagement & Culture",
    "Survey action plans are not closed",
    "Leaders run a census, publish themes, and do not complete the committed actions before the next survey.",
    "Survey-to-action gap",
    "https://www.gallup.com/workplace/",
    ["engagement_index", "change_adoption", "manager_effectiveness"],
  ],
  [
    "ec-prob-hybrid-01",
    "problem",
    "Engagement & Culture",
    "Hybrid teams report isolation and unclear priorities",
    "Hybrid employees report weaker connection and goal clarity than on-site peers.",
    "Hybrid work experience pattern",
    "https://www.gallup.com/workplace/",
    ["engagement_index", "manager_effectiveness", "wellbeing_index"],
  ],
  [
    "ec-prob-recog-01",
    "problem",
    "Engagement & Culture",
    "Recognition is uneven and manager-dependent",
    "Recognition programs exist, but usage and favorable scores cluster in a few teams.",
    "Culture-in-daily-work gap (Gartner framing)",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["engagement_index", "manager_effectiveness", "inclusion_index"],
  ],
  [
    "ec-prob-values-01",
    "problem",
    "Engagement & Culture",
    "Values are not visible in promotion and exit data",
    "The company talks about values, but promotion and regrettable-exit patterns do not match the stated culture.",
    "Gartner culture atrophy risk",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["promotion_rate", "regrettable_attrition", "engagement_index"],
  ],
  [
    "ec-prob-trust-01",
    "problem",
    "Engagement & Culture",
    "Trust in leadership declined during uncertainty",
    "Leadership-trust items fell while operational KPIs were still met, creating a delayed retention risk.",
    "SHRM 2026 culture and leadership pressure",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["engagement_index", "enps", "regrettable_attrition"],
  ],
  [
    "dei-slate-01",
    "strategy",
    "DEI",
    "Improve representation on leadership interview slates",
    "Meet the approved slate standard for leadership searches. This is a process metric, not a prediction about individuals.",
    "SHRM / lawful diversity process practice",
    "https://www.shrm.org/",
    ["representation", "internal_fill", "inclusion_index"],
    "Leadership slates",
  ],
  [
    "dei-process-01",
    "strategy",
    "DEI",
    "Close adverse impact in hiring process stages",
    "Measure stage-pass rates against the approved fairness standard and fix process design, not individual profiling.",
    "CIPD / equal-opportunity process analytics",
    "https://www.cipd.org/en/knowledge/factsheets/diversity-factsheet/",
    ["representation", "offer_acceptance", "candidate_satisfaction"],
  ],
  [
    "dei-inclusion-01",
    "strategy",
    "DEI",
    "Strengthen inclusion climate through managers",
    "Raise inclusion-index scores by improving manager fairness and voice, with small-group suppression rules.",
    "Gallup belonging / CIPD inclusion practice",
    "https://www.gallup.com/workplace/",
    ["inclusion_index", "manager_effectiveness", "engagement_index"],
  ],
  [
    "dei-pay-01",
    "strategy",
    "DEI",
    "Run a controlled pay-equity review on a fixed cadence",
    "Measure residual pay gaps after job, level, and location controls, and close documented exceptions.",
    "ISO 30414 / pay-equity reporting practice",
    "https://www.iso.org/standard/69338.html",
    ["pay_equity", "compa_ratio", "data_completeness"],
  ],
  [
    "dei-prob-slate-01",
    "problem",
    "DEI",
    "Diverse slates stall at interview",
    "Intake slates meet the process standard, then pass-through drops at interview without a documented reason.",
    "Process-stage fairness problem",
    "https://www.cipd.org/en/knowledge/factsheets/diversity-factsheet/",
    ["representation", "interview_scheduling", "hiring_manager_satisfaction"],
  ],
  [
    "dei-prob-inclusion-01",
    "problem",
    "DEI",
    "Inclusion scores lag in specific teams",
    "Inclusion items are below threshold in identifiable teams. Action is manager and process quality, not individual prediction.",
    "Inclusion climate problem",
    "https://www.gallup.com/workplace/",
    ["inclusion_index", "manager_effectiveness", "regrettable_attrition"],
  ],
  [
    "dei-prob-pay-01",
    "problem",
    "DEI",
    "Pay equity review is annual and residual gaps persist",
    "The company runs one annual model and does not refresh after merit or hiring cycles.",
    "Pay-equity operating cadence problem",
    "https://www.iso.org/standard/69338.html",
    ["pay_equity", "compa_ratio", "process_cycle_time"],
  ],
  [
    "dei-prob-promo-01",
    "problem",
    "DEI",
    "Promotion rates are uneven after controls",
    "Promotion outcomes differ after job and performance controls. Investigate process, not protected-class prediction models.",
    "Advancement process problem",
    "https://www.cipd.org/en/knowledge/factsheets/diversity-factsheet/",
    ["promotion_rate", "inclusion_index", "bench_strength"],
  ],
  [
    "dei-prob-retention-01",
    "problem",
    "DEI",
    "Retention is weaker in underrepresented cohorts after process checks",
    "If a lawful, approved analysis shows retention gaps, treat manager quality, mobility, and pay process as the levers.",
    "Retention process fairness",
    "https://www.shrm.org/",
    ["regrettable_attrition", "inclusion_index", "internal_mobility"],
  ],
  [
    "dei-prob-data-01",
    "problem",
    "DEI",
    "Self-ID and slate data are too incomplete to report",
    "Process metrics cannot be calculated because required fields fail completeness or suppression rules.",
    "Evidence-boundary problem",
    "https://www.iso.org/standard/69338.html",
    ["data_completeness", "representation", "inclusion_index"],
  ],
  [
    "wp-dynamic-01",
    "strategy",
    "Workforce Planning",
    "Replace static headcount plans with dynamic workforce planning",
    "Refresh supply, demand, and scenario plans on a monthly rhythm, including skills and contingent labor.",
    "Deloitte — reinventing workforce planning; Gartner SWP confidence gap",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["headcount_vs_plan", "skills_coverage", "contractor_ratio", "overall_attrition"],
  ],
  [
    "wp-skill-demand-01",
    "strategy",
    "Workforce Planning",
    "Align headcount to demand by skill, not only by cost center",
    "Translate business demand into skill FTE and compare with the latest employee snapshot.",
    "Deloitte autonomous / dynamic workforce planning",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/autonomous-workforce-planning.html",
    ["headcount_vs_plan", "critical_skill_gap", "workforce_cost"],
  ],
  [
    "wp-bbbb-01",
    "strategy",
    "Workforce Planning",
    "Balance build, buy, borrow, and bot for constrained work",
    "For each critical skill, record whether the plan is to develop, hire, contract, or automate, and track execution.",
    "Classic SWP lever set, restated for AI-era work design",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["skills_coverage", "time_to_fill", "contractor_ratio", "ai_adoption"],
  ],
  [
    "wp-contingent-01",
    "strategy",
    "Workforce Planning",
    "Govern contractor and vendor mix against an approved range",
    "Set a contractor-ratio range by work type and review monthly snapshot mix versus plan.",
    "Blended workforce governance",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["contractor_ratio", "workforce_cost", "headcount_vs_plan"],
  ],
  [
    "wp-hc-01",
    "strategy",
    "Workforce Planning",
    "Keep monthly headcount within plan while explaining movement",
    "Use employee × month snapshots to explain MoM and YoY movement before changing the hiring process.",
    "ISO 30414 workforce composition / local snapshot practice",
    "https://www.iso.org/standard/69338.html",
    ["headcount_vs_plan", "overall_attrition", "time_to_fill"],
  ],
  [
    "wp-prob-over-under-01",
    "problem",
    "Workforce Planning",
    "Headcount is over plan in some units and under in others",
    "The company total looks fine, but local snapshots show surplus and shortage in the same month.",
    "Plan-versus-actual composition problem",
    "https://www.iso.org/standard/69338.html",
    ["headcount_vs_plan", "span_of_control", "workforce_cost"],
  ],
  [
    "wp-prob-confidence-01",
    "problem",
    "Workforce Planning",
    "Leaders are not confident in the workforce plan",
    "Gartner has reported that only a minority of CHROs feel confident delivering SWP goals. This org feels the same gap.",
    "Gartner SWP confidence finding, cited in Deloitte workforce planning",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["headcount_vs_plan", "data_completeness", "skills_coverage"],
  ],
  [
    "wp-prob-snapshot-01",
    "problem",
    "Workforce Planning",
    "Snapshot files answer headcount, not hiring speed",
    "Leaders asked why hiring is slow, but the available extract is an employee monthly snapshot without requisition dates.",
    "Evidence-boundary problem in People analytics",
    "https://www.cipd.org/en/knowledge/factsheets/people-analytics-factsheet/",
    ["headcount_vs_plan", "time_to_fill", "data_completeness"],
  ],
  [
    "wp-prob-contractor-01",
    "problem",
    "Workforce Planning",
    "Contractor ratio drifted without a decision",
    "Contingent mix rose as a workaround for hiring delays and was never reset to the approved range.",
    "Blended workforce drift",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["contractor_ratio", "time_to_fill", "workforce_cost"],
  ],
  [
    "wp-prob-forecast-01",
    "problem",
    "Workforce Planning",
    "Demand forecast is not linked to skills",
    "Finance sends FTE targets; People cannot translate them into skill supply or hiring reqs.",
    "Deloitte SWP integration problem",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["headcount_vs_plan", "critical_skill_gap", "time_to_fill"],
  ],
  [
    "wp-prob-attrition-assume-01",
    "problem",
    "Workforce Planning",
    "Attrition assumptions in the plan are stale",
    "The annual plan still uses last year's attrition rate even though recent snapshots show a different trend.",
    "Planning-assumption hygiene",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/autonomous-workforce-planning.html",
    ["overall_attrition", "headcount_vs_plan", "regrettable_attrition"],
  ],
  [
    "wp-prob-scenario-01",
    "problem",
    "Workforce Planning",
    "There is no scenario plan for hiring freeze or surge",
    "Leaders ask what happens if demand drops 10% or a product line doubles, and People cannot simulate it.",
    "Scenario-planning gap",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["headcount_vs_plan", "workforce_cost", "contractor_ratio"],
  ],
  [
    "comp-equity-01",
    "strategy",
    "Compensation",
    "Improve pay-equity transparency with a controlled model",
    "Publish the approved method and close residual gaps on a quarterly exception process.",
    "ISO 30414 human-capital disclosure practice",
    "https://www.iso.org/standard/69338.html",
    ["pay_equity", "compa_ratio", "data_completeness"],
  ],
  [
    "comp-skills-01",
    "strategy",
    "Compensation",
    "Align rewards to scarce skills, not only tenure",
    "Use skills premiums and range placement so scarce capability is not paid like a generic job title.",
    "Skills-based rewards practice",
    "https://joshbersin.com/",
    ["compa_ratio", "retention_critical", "skills_coverage"],
  ],
  [
    "comp-offer-speed-01",
    "strategy",
    "Compensation",
    "Shorten compensation approval in the offer cycle",
    "Cut offer-comp cycle time so approval is not the reason candidates accept elsewhere.",
    "TA and total-rewards operations",
    "https://www.cipd.org/en/knowledge/factsheets/reward-factsheet/",
    ["offer_approval", "offer_acceptance", "process_cycle_time"],
  ],
  [
    "comp-prob-mid-01",
    "problem",
    "Compensation",
    "Compa-ratios sit below midpoint for scarce skills",
    "Employees in named scarce skills cluster below 0.90 while the external market has moved.",
    "Range-penetration problem",
    "https://www.cipd.org/en/knowledge/factsheets/reward-factsheet/",
    ["compa_ratio", "retention_critical", "regrettable_attrition"],
  ],
  [
    "comp-prob-annual-01",
    "problem",
    "Compensation",
    "Pay decisions wait for the annual cycle",
    "Off-cycle corrections are rare, so inequity and market gaps persist for 12 months.",
    "Rewards cadence problem",
    "https://www.shrm.org/",
    ["pay_equity", "process_cycle_time", "regrettable_attrition"],
  ],
  [
    "comp-prob-offer-01",
    "problem",
    "Compensation",
    "Offer compensation approvals take too long",
    "Compensation and finance approvals add days after the hiring manager has already selected a finalist.",
    "Offer-cycle rewards bottleneck",
    "https://www.linkedin.com/business/talent/blog",
    ["offer_approval", "offer_acceptance", "time_to_fill"],
  ],
  [
    "comp-prob-bonus-01",
    "problem",
    "Compensation",
    "Retention bonuses are untargeted",
    "Stay bonuses are paid broadly, but regrettable attrition continues in the critical-skill set.",
    "Inefficient retention spend",
    "https://www.cipd.org/en/knowledge/factsheets/reward-factsheet/",
    ["regrettable_attrition", "retention_critical", "workforce_cost"],
  ],
  [
    "comp-prob-range-01",
    "problem",
    "Compensation",
    "Job ranges are outdated after a skills redesign",
    "Work was redesigned, but ranges still follow the old job architecture.",
    "Job architecture lag",
    "https://www.deloitte.com/us/en/insights/topics/talent/future-of-workforce-planning/reinventing-workforce-planning.html",
    ["compa_ratio", "pay_equity", "data_completeness"],
  ],
  [
    "pf-ai-quality-01",
    "strategy",
    "Performance",
    "Redefine performance beyond volume in AI-enabled work",
    "Add quality, judgment, and rework measures so speed of AI output is not the only performance signal.",
    "2026 human-machine performance risk (Gartner-aligned)",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["high_performer_retention", "quality_of_hire", "ai_adoption"],
  ],
  [
    "pf-retain-hp-01",
    "strategy",
    "Performance",
    "Retain and grow high performers",
    "Keep high-performer retention above the guardrail and move more of them into succession plans.",
    "Performance and talent-review practice",
    "https://www.cipd.org/en/knowledge/factsheets/performance-factsheet/",
    ["high_performer_retention", "promotion_rate", "bench_strength"],
  ],
  [
    "pf-calibrate-01",
    "strategy",
    "Performance",
    "Improve calibration fairness and usefulness",
    "Run calibration with an approved standard so ratings can be used in pay and succession without compression theater.",
    "CIPD performance management practice",
    "https://www.cipd.org/en/knowledge/factsheets/performance-factsheet/",
    ["high_performer_retention", "pay_equity", "data_completeness"],
  ],
  [
    "pf-goals-01",
    "strategy",
    "Performance",
    "Tie team goals to the approved strategy metric",
    "Every priority team has a goal that maps to an approved outcome or driver metric.",
    "Strategy-to-goal cascade practice",
    "https://www.mckinsey.com/capabilities/people-and-organizational-performance",
    ["engagement_index", "change_adoption", "headcount_vs_plan"],
  ],
  [
    "pf-prob-compress-01",
    "problem",
    "Performance",
    "Performance ratings are compressed",
    "Almost everyone is rated the same, so high-performer retention and pay differentiation cannot be measured.",
    "Rating-system failure",
    "https://www.cipd.org/en/knowledge/factsheets/performance-factsheet/",
    ["high_performer_retention", "data_completeness", "pay_equity"],
  ],
  [
    "pf-prob-succession-01",
    "problem",
    "Performance",
    "High performers are missing from succession plans",
    "People rated highly are not on benches, and benches are filled with convenient names.",
    "Talent-review integrity problem",
    "https://www.cipd.org/en/knowledge/factsheets/succession-planning-factsheet/",
    ["bench_strength", "high_performer_retention", "succession_readiness"],
  ],
  [
    "pf-prob-goals-01",
    "problem",
    "Performance",
    "Goals are not tied to the strategy question",
    "Team goals optimize local activity and do not move the approved People outcome metric.",
    "Strategy-measurement disconnect",
    "https://www.cipd.org/en/knowledge/factsheets/people-analytics-factsheet/",
    ["change_adoption", "engagement_index", "data_completeness"],
  ],
  [
    "pf-prob-cycle-01",
    "problem",
    "Performance",
    "The review cycle is too slow for the work",
    "Annual reviews arrive after project outcomes are stale, especially in AI-enabled teams.",
    "Performance-cycle lag",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["process_cycle_time", "ai_adoption", "high_performer_retention"],
  ],
  [
    "wb-burnout-01",
    "strategy",
    "Wellbeing",
    "Reduce burnout risk in AI-transformed roles",
    "Treat cognitive load and recovery as performance enablers. Measure wellbeing beside AI adoption.",
    "Gartner 2026 human-machine era / 2026 HR commentary on cognitive load",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["wellbeing_index", "overtime_rate", "ai_adoption"],
    "AI-transformed roles",
  ],
  [
    "wb-workload-01",
    "strategy",
    "Wellbeing",
    "Make sustainable workload an explicit guardrail",
    "No transformation or hiring-speed goal may proceed if overtime and wellbeing breach the guardrail.",
    "CIPD wellbeing at work practice",
    "https://www.cipd.org/en/knowledge/factsheets/well-being-factsheet/",
    ["wellbeing_index", "overtime_rate", "absence_rate"],
  ],
  [
    "wb-absence-01",
    "strategy",
    "Wellbeing",
    "Improve absence predictability and support",
    "Use absence trends as a workload and health-system signal, not as an individual scorecard.",
    "CIPD absence management practice",
    "https://www.cipd.org/en/knowledge/factsheets/absence-factsheet/",
    ["absence_rate", "wellbeing_index", "overtime_rate"],
  ],
  [
    "wb-prob-ot-01",
    "problem",
    "Wellbeing",
    "Overtime is chronic in one function",
    "One function has been above the overtime threshold for three or more months.",
    "Workload concentration problem",
    "https://www.cipd.org/en/knowledge/factsheets/well-being-factsheet/",
    ["overtime_rate", "absence_rate", "regrettable_attrition"],
  ],
  [
    "wb-prob-absence-01",
    "problem",
    "Wellbeing",
    "Absence spikes after change programs",
    "Absence rises in units after major system or AI rollouts.",
    "Change-load health signal",
    "https://www.shrm.org/executive-network/insights/research/2026-will-test-hr-january-2026-en-insights-forum-recap",
    ["absence_rate", "change_adoption", "wellbeing_index"],
  ],
  [
    "wb-prob-ai-01",
    "problem",
    "Wellbeing",
    "Wellbeing scores fell as AI rollout accelerated",
    "Adoption metrics improved while recovery and workload items declined.",
    "Human-machine wellbeing tradeoff",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["wellbeing_index", "ai_adoption", "overtime_rate"],
  ],
  [
    "wb-prob-afterhours-01",
    "problem",
    "Wellbeing",
    "After-hours messages are rising",
    "Collaboration tools show more nights-and-weekend traffic in teams already reporting load issues.",
    "Always-on work risk",
    "https://www.cipd.org/en/knowledge/factsheets/well-being-factsheet/",
    ["wellbeing_index", "overtime_rate", "engagement_index"],
  ],
  [
    "wb-prob-eap-01",
    "problem",
    "Wellbeing",
    "Support programs exist but are unused in high-load teams",
    "EAP or wellbeing offerings have low take-up in the teams with the worst overtime and absence.",
    "Program-to-need mismatch",
    "https://www.cipd.org/en/knowledge/factsheets/well-being-factsheet/",
    ["wellbeing_index", "absence_rate", "data_completeness"],
  ],
  [
    "po-iso-01",
    "strategy",
    "People Operations",
    "Improve People data completeness for decision-grade reporting",
    "Bring metric-required fields to an approved completeness standard before claiming ISO 30414-style readiness.",
    "ISO 30414 human capital reporting",
    "https://www.iso.org/standard/69338.html",
    ["data_completeness", "headcount_vs_plan", "process_cycle_time"],
  ],
  [
    "po-sla-01",
    "strategy",
    "People Operations",
    "Meet published SLAs for core People processes",
    "Measure cycle time for hiring support, employee changes, and case work against the published SLA.",
    "HR operating-model service practice",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["process_cycle_time", "hiring_manager_satisfaction", "enps"],
  ],
  [
    "po-ai-hr-01",
    "strategy",
    "People Operations",
    "Raise productive AI adoption inside the HR operating model",
    "Adopt AI in HR work where the operating model is redesigned, not only where a tool was purchased.",
    "Gartner 2026 — harness AI to revolutionize HR",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["ai_adoption", "process_cycle_time", "data_completeness"],
  ],
  [
    "po-self-01",
    "strategy",
    "People Operations",
    "Shift routine transactions to self-service without losing completeness",
    "Increase self-service for simple changes while holding data-completeness and cycle-time standards.",
    "HR service delivery practice",
    "https://www.cipd.org/en/knowledge/factsheets/",
    ["process_cycle_time", "data_completeness", "enps"],
  ],
  [
    "po-prob-quality-01",
    "problem",
    "People Operations",
    "Employee data quality blocks analytics",
    "Joins fail because identifiers, dates, or status flags are incomplete, so answerability stays low.",
    "CIPD people analytics practice",
    "https://www.cipd.org/en/knowledge/factsheets/people-analytics-factsheet/",
    ["data_completeness", "headcount_vs_plan", "time_to_fill"],
  ],
  [
    "po-prob-sla-01",
    "problem",
    "People Operations",
    "People process SLAs are missed",
    "Employee changes, letters, or hiring support regularly exceed the published cycle time.",
    "HR operations SLA miss",
    "https://www.shrm.org/",
    ["process_cycle_time", "hiring_manager_satisfaction", "enps"],
  ],
  [
    "po-prob-ai-unused-01",
    "problem",
    "People Operations",
    "HR AI tools are licensed but unused",
    "Seats were bought. Active use and process redesign did not follow.",
    "Gartner AI productivity depends on operating-model change",
    "https://www.gartner.com/en/human-resources/trends/top-priorities-for-hr-leaders",
    ["ai_adoption", "process_cycle_time", "change_adoption"],
  ],
  [
    "po-prob-exceptions-01",
    "problem",
    "People Operations",
    "Policy exceptions are undocumented",
    "Offers, pay, and worker-type exceptions are granted in email and never reach the system of record.",
    "Control and completeness problem",
    "https://www.iso.org/standard/69338.html",
    ["data_completeness", "pay_equity", "contractor_ratio"],
  ],
  [
    "po-prob-duplicate-01",
    "problem",
    "People Operations",
    "The same employee exists under multiple identifiers",
    "Snapshot, payroll, and recruiting files cannot be joined reliably.",
    "Identity-resolution gap",
    "https://www.cipd.org/en/knowledge/factsheets/people-analytics-factsheet/",
    ["data_completeness", "headcount_vs_plan", "quality_of_hire"],
  ],
  [
    "po-prob-privacy-01",
    "problem",
    "People Operations",
    "Raw People files are being copied into shared drives",
    "Email and name columns travel with extracts. Local-first processing and redaction are not the default.",
    "Privacy operating standard",
    "https://www.iso.org/standard/69338.html",
    ["data_completeness", "process_cycle_time"],
  ],
];

function toItem(row: CatalogRow): CatalogItem {
  const [id, kind, category, title, statement, source, sourceUrl, metricIds, population] =
    row;
  return {
    id,
    kind,
    category,
    title,
    statement,
    source,
    sourceUrl,
    metricIds,
    population,
  };
}

export const strategyCatalog: CatalogItem[] = rows.map(toItem);

export const strategyCategories: StrategyCategory[] = [
  "Talent Acquisition",
  "Retention",
  "Skills & Capability",
  "Leadership",
  "Internal Mobility",
  "Engagement & Culture",
  "DEI",
  "Workforce Planning",
  "Compensation",
  "Performance",
  "Wellbeing",
  "People Operations",
];

export function getCatalogItem(id: string) {
  return strategyCatalog.find((item) => item.id === id);
}

export function filterCatalog(
  items: CatalogItem[],
  query: string,
  kind?: StrategyIntent,
  category?: StrategyCategory | "All",
) {
  const normalized = query.trim().toLowerCase();
  return items.filter((item) => {
    if (kind && item.kind !== kind) return false;
    if (category && category !== "All" && item.category !== category) return false;
    if (!normalized) return true;
    return `${item.title} ${item.statement} ${item.category} ${item.source}`
      .toLowerCase()
      .includes(normalized);
  });
}

export function catalogStats() {
  const byKind = { strategy: 0, problem: 0 };
  const byCategory = Object.fromEntries(
    strategyCategories.map((category) => [category, 0]),
  ) as Record<StrategyCategory, number>;
  for (const item of strategyCatalog) {
    byKind[item.kind] += 1;
    byCategory[item.category] += 1;
  }
  return { total: strategyCatalog.length, byKind, byCategory };
}
