import type { MetricTemplate } from "@/types/strategy";

export const metricTemplates: Record<string, MetricTemplate> = {
  time_to_fill: {
    id: "time_to_fill",
    name: "Time to Fill",
    category: "Outcome",
    definition: "Elapsed calendar days from requisition open to accepted offer.",
    measurementStandard:
      "Median days, completed requisitions only. Open roles and withdrawn offers are excluded.",
    formula: "offer_accepted_at − requisition_open_date",
    unit: "days",
    requiredFields: ["requisition_id", "requisition_open_date", "offer_accepted_at"],
    suggestedTarget: "45 days",
    confidence: "High",
  },
  time_to_hire: {
    id: "time_to_hire",
    name: "Time to Hire",
    category: "Driver",
    definition: "Elapsed calendar days from application to hire or start date.",
    measurementStandard:
      "Median days for completed hires. This is an observed proxy, not Time to Fill.",
    formula: "hire_date − application_date",
    unit: "days",
    requiredFields: ["candidate_id", "application_date", "hire_date"],
    suggestedTarget: "30 days",
    confidence: "High",
  },
  quality_of_hire: {
    id: "quality_of_hire",
    name: "Quality of Hire",
    category: "Guardrail",
    definition:
      "Weighted first-year performance, 12-month retention, and hiring-manager satisfaction.",
    measurementStandard:
      "Index 0–100 on hires with 6+ months tenure. Do not report until the cohort is large enough.",
    formula: "performance × 50% + retained_12m × 30% + manager_satisfaction × 20%",
    unit: "index",
    requiredFields: ["employee_id", "performance_rating", "retained_12m", "manager_satisfaction"],
    suggestedTarget: "≥ 76",
    confidence: "Medium",
  },
  offer_acceptance: {
    id: "offer_acceptance",
    name: "Offer Acceptance Rate",
    category: "Guardrail",
    definition: "Accepted offers divided by extended offers.",
    measurementStandard: "Percent of offers extended in the period, excluding expired drafts.",
    formula: "accepted_offers ÷ extended_offers",
    unit: "%",
    requiredFields: ["offer_extended_at", "offer_accepted_at"],
    suggestedTarget: "≥ 85%",
    confidence: "High",
  },
  candidate_satisfaction: {
    id: "candidate_satisfaction",
    name: "Candidate Satisfaction",
    category: "Guardrail",
    definition: "Average post-decision candidate survey rating.",
    measurementStandard: "Mean overall score for decided candidates, hired and declined.",
    formula: "mean(overall_satisfaction)",
    unit: "score",
    requiredFields: ["survey_event", "overall_satisfaction"],
    suggestedTarget: "≥ 4.1 / 5",
    confidence: "Medium",
  },
  cost_per_hire: {
    id: "cost_per_hire",
    name: "Cost per Hire",
    category: "Driver",
    definition: "Internal and external recruiting cost allocated to completed hires.",
    measurementStandard: "Period recruiting spend divided by completed hires. Agency fees included.",
    formula: "recruiting_spend ÷ completed_hires",
    unit: "currency",
    requiredFields: ["recruiting_spend", "hire_date"],
    suggestedTarget: "At or below prior-year median",
    confidence: "Medium",
  },
  source_effectiveness: {
    id: "source_effectiveness",
    name: "Source Effectiveness",
    category: "Driver",
    definition: "Hire rate and Quality of Hire by candidate source.",
    measurementStandard: "Report only sources with at least 25 applications in the period.",
    formula: "hires_by_source ÷ applications_by_source",
    unit: "%",
    requiredFields: ["source", "application_date", "hire_date"],
    suggestedTarget: "No single source > 50% of hires",
    confidence: "Medium",
  },
  requisition_aging: {
    id: "requisition_aging",
    name: "Requisition Aging",
    category: "Driver",
    definition: "Share of open requisitions older than the agreed SLA.",
    measurementStandard: "Open reqs with no accepted offer, aged from requisition open date.",
    formula: "open_reqs_over_sla ÷ open_reqs",
    unit: "%",
    requiredFields: ["requisition_id", "requisition_open_date", "req_status"],
    suggestedTarget: "< 15% older than 60 days",
    confidence: "High",
  },
  time_to_first_qualified: {
    id: "time_to_first_qualified",
    name: "Time to First Qualified Candidate",
    category: "Driver",
    definition: "Days from requisition open to first candidate marked qualified.",
    measurementStandard: "Median days. Requires a consistent qualified-slate definition.",
    formula: "first_qualified_at − requisition_open_date",
    unit: "days",
    requiredFields: ["requisition_open_date", "qualified_at"],
    suggestedTarget: "14 days",
    confidence: "Medium",
  },
  interview_scheduling: {
    id: "interview_scheduling",
    name: "Interview Scheduling Time",
    category: "Driver",
    definition: "Days from interview request to confirmed schedule.",
    measurementStandard: "Median completed scheduling intervals. Canceled loops excluded.",
    formula: "interview_scheduled_at − interview_requested_at",
    unit: "days",
    requiredFields: ["interview_requested_at", "interview_scheduled_at"],
    suggestedTarget: "6 days",
    confidence: "High",
  },
  offer_approval: {
    id: "offer_approval",
    name: "Offer Approval Time",
    category: "Driver",
    definition: "Days from offer creation to final approval.",
    measurementStandard: "Median approved offers. Drafts never submitted are excluded.",
    formula: "offer_approved_at − offer_created_at",
    unit: "days",
    requiredFields: ["offer_created_at", "offer_approved_at"],
    suggestedTarget: "6 days",
    confidence: "High",
  },
  first_year_attrition: {
    id: "first_year_attrition",
    name: "First-year Attrition",
    category: "Outcome",
    definition: "Share of hires who leave within 12 months of start date.",
    measurementStandard: "Cohort rate for hires with 12 months of observation. Do not annualize partial cohorts.",
    formula: "exits_within_12m ÷ hires_in_cohort",
    unit: "%",
    requiredFields: ["employee_id", "hire_date", "termination_date"],
    suggestedTarget: "≤ 12%",
    confidence: "High",
  },
  regrettable_attrition: {
    id: "regrettable_attrition",
    name: "Regrettable Attrition",
    category: "Outcome",
    definition: "Voluntary exits among employees the organization wanted to retain.",
    measurementStandard:
      "Requires an approved regrettable definition. Do not infer from performance alone.",
    formula: "regrettable_exits ÷ average_headcount",
    unit: "%",
    requiredFields: ["employee_id", "termination_date", "regrettable_flag"],
    suggestedTarget: "≤ 6%",
    confidence: "Medium",
  },
  overall_attrition: {
    id: "overall_attrition",
    name: "Overall Attrition",
    category: "Driver",
    definition: "All separations in the period divided by average headcount.",
    measurementStandard: "Monthly or quarterly annualized rate, consistently defined.",
    formula: "separations ÷ average_headcount",
    unit: "%",
    requiredFields: ["employee_id", "snapshot_month", "termination_date"],
    suggestedTarget: "At or below historical median",
    confidence: "High",
  },
  retention_critical: {
    id: "retention_critical",
    name: "Critical-role Retention",
    category: "Outcome",
    definition: "Retention rate for employees in designated critical roles or skills.",
    measurementStandard: "Critical-role list must be approved before reporting.",
    formula: "retained_critical ÷ critical_population",
    unit: "%",
    requiredFields: ["employee_id", "critical_role_flag", "employment_status"],
    suggestedTarget: "≥ 92%",
    confidence: "Medium",
  },
  enps: {
    id: "enps",
    name: "eNPS",
    category: "Guardrail",
    definition: "Employee Net Promoter Score from the latest census or pulse.",
    measurementStandard: "Promoters minus detractors. Report response rate beside the score.",
    formula: "% promoters − % detractors",
    unit: "index",
    requiredFields: ["survey_event", "nps_score"],
    suggestedTarget: "≥ +20",
    confidence: "Medium",
  },
  engagement_index: {
    id: "engagement_index",
    name: "Engagement Index",
    category: "Outcome",
    definition: "Composite favorable score on approved engagement items.",
    measurementStandard: "Use the same item set over time. Break out by manager, not protected class, for action.",
    formula: "mean(favorable_engagement_items)",
    unit: "% favorable",
    requiredFields: ["survey_event", "engagement_item_score"],
    suggestedTarget: "≥ 70% favorable",
    confidence: "Medium",
  },
  manager_effectiveness: {
    id: "manager_effectiveness",
    name: "Manager Effectiveness",
    category: "Driver",
    definition: "Team-level score for manager coaching, clarity, and support.",
    measurementStandard: "Suppress teams below the minimum response threshold.",
    formula: "mean(manager_items)",
    unit: "% favorable",
    requiredFields: ["survey_event", "manager_id", "manager_item_score"],
    suggestedTarget: "≥ 75% favorable",
    confidence: "Medium",
  },
  internal_fill: {
    id: "internal_fill",
    name: "Internal Fill Rate",
    category: "Outcome",
    definition: "Share of filled requisitions awarded to internal candidates.",
    measurementStandard: "Filled reqs in period. External-only reqs should be flagged, not hidden.",
    formula: "internal_hires ÷ filled_requisitions",
    unit: "%",
    requiredFields: ["requisition_id", "internal_candidate_flag", "hire_date"],
    suggestedTarget: "≥ 40%",
    confidence: "High",
  },
  internal_mobility: {
    id: "internal_mobility",
    name: "Internal Mobility Rate",
    category: "Driver",
    definition: "Employees making a role, level, or location move in the period.",
    measurementStandard: "Count one primary move per employee per year.",
    formula: "employees_with_move ÷ average_headcount",
    unit: "%",
    requiredFields: ["employee_id", "job_change_date", "job_change_type"],
    suggestedTarget: "≥ 12%",
    confidence: "Medium",
  },
  time_to_productivity: {
    id: "time_to_productivity",
    name: "Time to Productivity",
    category: "Driver",
    definition: "Days from start date to the approved productivity milestone.",
    measurementStandard: "Milestone must be role-specific and approved. Do not use manager opinion alone.",
    formula: "productivity_milestone_at − hire_date",
    unit: "days",
    requiredFields: ["hire_date", "productivity_milestone_at"],
    suggestedTarget: "90 days for standard roles",
    confidence: "Low",
  },
  skills_coverage: {
    id: "skills_coverage",
    name: "Critical Skills Coverage",
    category: "Outcome",
    definition: "Share of demanded critical skills with sufficient proficient supply.",
    measurementStandard: "Demand and proficiency scales must be approved. Self-ratings alone are Low confidence.",
    formula: "covered_critical_skills ÷ demanded_critical_skills",
    unit: "%",
    requiredFields: ["skill_id", "demand_flag", "proficiency_level"],
    suggestedTarget: "≥ 80%",
    confidence: "Low",
  },
  critical_skill_gap: {
    id: "critical_skill_gap",
    name: "Critical Skill Gap",
    category: "Driver",
    definition: "Count or FTE shortfall for named critical skills.",
    measurementStandard: "Report the approved skill list and the as-of date.",
    formula: "required_fte − proficient_fte",
    unit: "FTE",
    requiredFields: ["skill_id", "required_fte", "proficient_fte"],
    suggestedTarget: "Close top 5 gaps this year",
    confidence: "Low",
  },
  learning_hours: {
    id: "learning_hours",
    name: "Learning Hours per Employee",
    category: "Driver",
    definition: "Completed formal learning hours in the period.",
    measurementStandard: "Hours completed, not assigned. Separate compliance from capability programs.",
    formula: "completed_learning_hours ÷ employees",
    unit: "hours",
    requiredFields: ["employee_id", "learning_hours"],
    suggestedTarget: "Context-specific; track completion quality, not hours alone",
    confidence: "Medium",
  },
  bench_strength: {
    id: "bench_strength",
    name: "Critical-role Bench Strength",
    category: "Outcome",
    definition: "Share of critical roles with at least one ready-now or ready-in-1-year successor.",
    measurementStandard: "Ready ratings must follow an approved succession standard.",
    formula: "critical_roles_with_successor ÷ critical_roles",
    unit: "%",
    requiredFields: ["critical_role_id", "successor_readiness"],
    suggestedTarget: "≥ 70%",
    confidence: "Medium",
  },
  succession_readiness: {
    id: "succession_readiness",
    name: "Succession Readiness",
    category: "Driver",
    definition: "Ready-now successors as a share of critical roles.",
    measurementStandard: "One named successor can cover only one primary role unless documented.",
    formula: "ready_now_successors ÷ critical_roles",
    unit: "ratio",
    requiredFields: ["critical_role_id", "successor_id", "readiness_level"],
    suggestedTarget: "≥ 1.0 ready-now per critical role",
    confidence: "Medium",
  },
  promotion_rate: {
    id: "promotion_rate",
    name: "Promotion Rate",
    category: "Driver",
    definition: "Employees promoted in the period divided by average headcount.",
    measurementStandard: "Use the approved promotion event. Lateral moves are reported separately.",
    formula: "promotions ÷ average_headcount",
    unit: "%",
    requiredFields: ["employee_id", "promotion_date"],
    suggestedTarget: "Compare with high-performer promotion rate",
    confidence: "High",
  },
  span_of_control: {
    id: "span_of_control",
    name: "Span of Control",
    category: "Driver",
    definition: "Direct reports per people manager.",
    measurementStandard: "Median and distribution. Exclude dotted-line unless the org model counts them.",
    formula: "direct_reports ÷ people_managers",
    unit: "ratio",
    requiredFields: ["employee_id", "manager_flag", "manager_id"],
    suggestedTarget: "Within the approved org-design range",
    confidence: "High",
  },
  pay_equity: {
    id: "pay_equity",
    name: "Pay Equity Gap",
    category: "Guardrail",
    definition: "Residual pay difference after approved job, level, and location controls.",
    measurementStandard:
      "Use a documented model. Do not treat raw group averages as the action metric.",
    formula: "controlled residual pay difference",
    unit: "%",
    requiredFields: ["employee_id", "base_pay", "job_level", "location"],
    suggestedTarget: "Within the approved equity threshold",
    confidence: "Medium",
  },
  compa_ratio: {
    id: "compa_ratio",
    name: "Compa-ratio",
    category: "Driver",
    definition: "Base pay divided by range midpoint.",
    measurementStandard: "Report median and share below 0.90 for scarce skills.",
    formula: "base_pay ÷ range_midpoint",
    unit: "ratio",
    requiredFields: ["employee_id", "base_pay", "range_midpoint"],
    suggestedTarget: "0.95–1.05 for proficient incumbents",
    confidence: "High",
  },
  high_performer_retention: {
    id: "high_performer_retention",
    name: "High-performer Retention",
    category: "Guardrail",
    definition: "Retention of employees in the approved high-performance group.",
    measurementStandard: "Performance group must be approved and stable across years.",
    formula: "retained_high_performers ÷ high_performers",
    unit: "%",
    requiredFields: ["employee_id", "performance_rating", "employment_status"],
    suggestedTarget: "≥ 95%",
    confidence: "Medium",
  },
  absence_rate: {
    id: "absence_rate",
    name: "Absence Rate",
    category: "Driver",
    definition: "Lost work time as a share of scheduled time.",
    measurementStandard: "Use scheduled hours as the denominator. Separate planned leave if needed.",
    formula: "absent_hours ÷ scheduled_hours",
    unit: "%",
    requiredFields: ["employee_id", "absent_hours", "scheduled_hours"],
    suggestedTarget: "At or below historical median",
    confidence: "Medium",
  },
  wellbeing_index: {
    id: "wellbeing_index",
    name: "Wellbeing Index",
    category: "Guardrail",
    definition: "Favorable score on approved workload, recovery, and support items.",
    measurementStandard: "Pulse or census. Report response rate. Do not diagnose individuals.",
    formula: "mean(wellbeing_items)",
    unit: "% favorable",
    requiredFields: ["survey_event", "wellbeing_item_score"],
    suggestedTarget: "≥ 70% favorable",
    confidence: "Medium",
  },
  overtime_rate: {
    id: "overtime_rate",
    name: "Overtime Rate",
    category: "Driver",
    definition: "Overtime hours as a share of worked hours.",
    measurementStandard: "Eligible populations only. Chronic overtime is a workload signal.",
    formula: "overtime_hours ÷ worked_hours",
    unit: "%",
    requiredFields: ["employee_id", "overtime_hours", "worked_hours"],
    suggestedTarget: "No team above the approved threshold for 3 months",
    confidence: "High",
  },
  representation: {
    id: "representation",
    name: "Leadership Slate Representation",
    category: "Outcome",
    definition: "Composition of interview or succession slates against the approved goal.",
    measurementStandard:
      "Process metric on slates, not a prediction about individuals. Use only approved, lawful categories.",
    formula: "slate_composition vs approved goal",
    unit: "%",
    requiredFields: ["slate_id", "role_level", "approved_composition_fields"],
    suggestedTarget: "Meet the approved slate standard",
    confidence: "Medium",
  },
  inclusion_index: {
    id: "inclusion_index",
    name: "Inclusion Index",
    category: "Guardrail",
    definition: "Favorable score on belonging, fairness, and voice items.",
    measurementStandard: "Suppress small groups. Action through process and manager quality, not profiling.",
    formula: "mean(inclusion_items)",
    unit: "% favorable",
    requiredFields: ["survey_event", "inclusion_item_score"],
    suggestedTarget: "≥ 70% favorable",
    confidence: "Medium",
  },
  headcount_vs_plan: {
    id: "headcount_vs_plan",
    name: "Headcount vs Plan",
    category: "Outcome",
    definition: "Actual employee snapshot headcount compared with the approved plan.",
    measurementStandard: "Same as-of month and workforce status definition. Contractors reported separately.",
    formula: "actual_headcount − plan_headcount",
    unit: "people",
    requiredFields: ["snapshot_month", "employee_id", "plan_headcount"],
    suggestedTarget: "Within ±2% of plan",
    confidence: "High",
  },
  contractor_ratio: {
    id: "contractor_ratio",
    name: "Contractor Ratio",
    category: "Driver",
    definition: "Contingent workers as a share of the blended workforce.",
    measurementStandard: "Use the approved worker-type mapping. Do not mix vendors and employees in one ID.",
    formula: "contractors ÷ (employees + contractors)",
    unit: "%",
    requiredFields: ["employment_category", "snapshot_month"],
    suggestedTarget: "Within the approved mix range",
    confidence: "Medium",
  },
  workforce_cost: {
    id: "workforce_cost",
    name: "Workforce Cost vs Plan",
    category: "Guardrail",
    definition: "Actual people cost compared with the approved budget.",
    measurementStandard: "Align Finance and People definitions of cost before reporting.",
    formula: "actual_people_cost − plan_people_cost",
    unit: "currency",
    requiredFields: ["people_cost", "plan_people_cost", "snapshot_month"],
    suggestedTarget: "Within the approved budget variance",
    confidence: "Medium",
  },
  change_adoption: {
    id: "change_adoption",
    name: "Change Adoption",
    category: "Outcome",
    definition: "Share of targeted employees using the new way of working as designed.",
    measurementStandard: "Requires an approved adoption definition per change program.",
    formula: "adopters ÷ targeted_employees",
    unit: "%",
    requiredFields: ["program_id", "adoption_flag"],
    suggestedTarget: "≥ 70% of targeted population",
    confidence: "Low",
  },
  ai_adoption: {
    id: "ai_adoption",
    name: "AI Tool Adoption",
    category: "Driver",
    definition: "Active use of approved AI tools in the targeted population.",
    measurementStandard: "Active users in the last 30 days, not licenses purchased.",
    formula: "active_ai_users ÷ licensed_employees",
    unit: "%",
    requiredFields: ["tool_id", "active_user_flag"],
    suggestedTarget: "Context-specific; pair with quality and wellbeing guardrails",
    confidence: "Low",
  },
  process_cycle_time: {
    id: "process_cycle_time",
    name: "HR Process Cycle Time",
    category: "Driver",
    definition: "Median elapsed time for a named People process.",
    measurementStandard: "Start and end events must be approved. Same definition every month.",
    formula: "process_end_at − process_start_at",
    unit: "days",
    requiredFields: ["process_id", "process_start_at", "process_end_at"],
    suggestedTarget: "Meet the published SLA",
    confidence: "High",
  },
  data_completeness: {
    id: "data_completeness",
    name: "People Data Completeness",
    category: "Driver",
    definition: "Share of required People fields populated for the reporting grain.",
    measurementStandard: "Required field list is approved. PII completeness is not a vanity score.",
    formula: "populated_required_fields ÷ required_fields",
    unit: "%",
    requiredFields: ["dataset_id", "required_field_status"],
    suggestedTarget: "≥ 95% on metric-required fields",
    confidence: "High",
  },
  hiring_manager_satisfaction: {
    id: "hiring_manager_satisfaction",
    name: "Hiring Manager Satisfaction",
    category: "Guardrail",
    definition: "Hiring-manager rating of slate quality and process.",
    measurementStandard: "Post-fill survey. Report only with a minimum response count.",
    formula: "mean(hm_satisfaction)",
    unit: "score",
    requiredFields: ["requisition_id", "hm_satisfaction"],
    suggestedTarget: "≥ 4.0 / 5",
    confidence: "Medium",
  },
};

export const metricTemplateList = Object.values(metricTemplates);
