export const PEOPLE_TABLE = {
  workspaces: "people_workspaces",
  datasets: "people_datasets",
  fieldMappings: "people_field_mappings",
  datasetRelationships: "people_dataset_relationships",
  workbenchMetrics: "people_workbench_metrics",
  analysisQuestions: "people_analysis_questions",
  insights: "people_insights",
  executiveStories: "people_executive_stories",
  aiUsage: "people_ai_usage",
  metricDefinition: "people_metric_definition",
  martWorkforceOverview: "people_mart_workforce_overview",
} as const;

export const PEOPLE_RPC = {
  consumeAiQuota: "people_consume_ai_quota",
  getMetric: "people_get_metric",
  getMetricTrend: "people_get_metric_trend",
  getMetricBreakdown: "people_get_metric_breakdown",
  getMetricDefinition: "people_get_metric_definition",
  getWorkforceOverview: "people_get_workforce_overview",
  getRetentionAnalysis: "people_get_retention_analysis",
  getMobilityAnalysis: "people_get_mobility_analysis",
  getRecruitingAnalysis: "people_get_recruiting_analysis",
  getLearningAnalysis: "people_get_learning_analysis",
  getSkillGap: "people_get_skill_gap",
  getLearningRecommendations: "people_get_learning_recommendations",
  getSourceHealth: "people_get_source_health",
  getQualityIncidents: "people_get_quality_incidents",
  traceMetricLineage: "people_trace_metric_lineage",
  getDataFoundation: "people_get_data_foundation",
  getPlatformFacts: "people_get_platform_facts",
  getServingSnapshot: "people_get_serving_snapshot",
  getQualityTests: "people_get_quality_tests",
} as const;
